package org.iets3.req.core.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import de.itemis.mps.editor.bool.runtime.CheckboxCellProvider;
import de.itemis.mps.editor.bool.runtime.EditorCell_Checkbox;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

/*package*/ class ReqChunkDetails_ComponentBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public ReqChunkDetails_ComponentBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_0();
  }

  private EditorCell createCollection_0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_73la3d_a");
    editorCell.addEditorCell(createConstant_0());
    editorCell.addEditorCell(createCollection_1());
    return editorCell;
  }
  private EditorCell createConstant_0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "Additional options:");
    editorCell.setCellId("Constant_73la3d_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_1() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_73la3d_b0");
    editorCell.addEditorCell(createCheckbox_1());
    editorCell.addEditorCell(createConstant_1());
    return editorCell;
  }
  private EditorCell createCheckbox_0(EditorContext editorContext, SNode node) {
    SProperty property = PROPS.hideEmptyChildReqsSection$guzy;
    CellProviderWithRole provider = new CheckboxCellProvider(node, property, editorContext);
    provider.setNoTargetText("<no hideEmptyChildReqsSection>");
    EditorCell_Checkbox editorCell;
    editorCell = ((EditorCell_Checkbox) provider.createEditorCell(editorContext));
    editorCell.setCellId("RCD_property_hideEmptyChildReqsSection");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      return getUpdateSession().updateAttributeCell(provider.getRoleAttributeKind(), editorCell, attributeConcept);
    } else
    return editorCell;
  }
  private EditorCell createCheckbox_1() {
    return createCheckbox_0(getEditorContext(), myNode);
  }
  private EditorCell createConstant_1() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "hide child requirements section, if empty");
    editorCell.setCellId("Constant_73la3d_b1a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private static final class PROPS {
    /*package*/ static final SProperty hideEmptyChildReqsSection$guzy = MetaAdapterFactory.getProperty(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc81949cL, 0x48f106e4a8e1b075L, "hideEmptyChildReqsSection");
  }
}
