package test.org.iets3.variability.configuration.base.editor;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import org.iets3.variability.configuration.base.plugin.FeatureModelIncludeUtil;
import org.junit.Assert;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import com.google.common.collect.Sets;
import jetbrains.mps.lang.test.runtime.CheckScopesAction;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.CollectionSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

@MPSLaunch
public class replaceWithExistingExternalConfig_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(replaceWithExistingExternalConfig_Test.class).projectPath(null).modelRef("r:c12bfe64-ecaf-4d6a-9f0c-0f5bfaf43528(test.org.iets3.variability.configuration.base.editor@tests)").reopenProject(null).build());

  public replaceWithExistingExternalConfig_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_unrestrictedByInheritedConfig() throws Throwable {
    new TestBody(this).test_unrestrictedByInheritedConfig();
  }
  @Test
  public void test_restrictedFeatureModelInlcudesDueToInheritedConfig() throws Throwable {
    new TestBody(this).test_restrictedFeatureModelInlcudesDueToInheritedConfig();
  }
  @Test
  public void test_unrestrictedByUnspecifiedNoInheritance() throws Throwable {
    new TestBody(this).test_unrestrictedByUnspecifiedNoInheritance();
  }
  @Test
  public void test_restrictedToEmptinessByInlineConfigOfExtendedConfig() throws Throwable {
    new TestBody(this).test_restrictedToEmptinessByInlineConfigOfExtendedConfig();
  }
  @Test
  public void test_unrestrictedByUnspecifiedInExtendedConfig() throws Throwable {
    new TestBody(this).test_unrestrictedByUnspecifiedInExtendedConfig();
  }
  @Test
  public void test_ScopeOf_FeatureModelConfigurationRef_config_2539572119535275055() throws Throwable {
    new TestBody(this).test_ScopeOf_FeatureModelConfigurationRef_config_2539572119535275055();
  }
  @Test
  public void test_ScopeOf_FeatureModelConfigurationRef_config_2539572119535275225() throws Throwable {
    new TestBody(this).test_ScopeOf_FeatureModelConfigurationRef_config_2539572119535275225();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    protected void initTestNodes() {
      prepareTestNodes("2539572119535275010");
    }

    public void test_unrestrictedByInheritedConfig() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        List<SNode> candidates = FeatureModelIncludeUtil.findEligibleIncludes(getAnnotatedNode("n"));
        Assert.assertEquals(2, ListSequence.fromList(candidates).count());

        Assert.assertEquals(Sets.newHashSet(getAnnotatedNode("cincl1"), getAnnotatedNode("cincl3")), Sets.newHashSet(candidates));
      });
    }
    public void test_restrictedFeatureModelInlcudesDueToInheritedConfig() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        List<SNode> candidates = FeatureModelIncludeUtil.findEligibleIncludes(getAnnotatedNode("n2"));
        Assert.assertEquals(1, ListSequence.fromList(candidates).count());

        SNode fmcObserved = ListSequence.fromList(candidates).getElement(0);
        Assert.assertEquals(getAnnotatedNode("cincl3"), fmcObserved);
      });
    }
    public void test_unrestrictedByUnspecifiedNoInheritance() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        List<SNode> candidates = FeatureModelIncludeUtil.findEligibleIncludes(getAnnotatedNode("n3"));
        Assert.assertEquals(3, ListSequence.fromList(candidates).count());

        Assert.assertEquals(Sets.newHashSet(getAnnotatedNode("cincl1"), getAnnotatedNode("cincl3"), getAnnotatedNode("cincl2")), Sets.newHashSet(candidates));
      });
    }
    public void test_restrictedToEmptinessByInlineConfigOfExtendedConfig() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        List<SNode> candidates = FeatureModelIncludeUtil.findEligibleIncludes(getAnnotatedNode("n4"));
        Assert.assertEquals(0, ListSequence.fromList(candidates).count());
      });
    }
    public void test_unrestrictedByUnspecifiedInExtendedConfig() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        List<SNode> candidates = FeatureModelIncludeUtil.findEligibleIncludes(getAnnotatedNode("n5"));
        Assert.assertEquals(3, ListSequence.fromList(candidates).count());

        Assert.assertEquals(Sets.newHashSet(getAnnotatedNode("cincl1"), getAnnotatedNode("cincl3"), getAnnotatedNode("cincl2")), Sets.newHashSet(candidates));
      });
    }
    public void test_ScopeOf_FeatureModelConfigurationRef_config_2539572119535275055() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getRealNodeById("2539572119535275055");
        new CheckScopesAction(nodeToCheck, MetaAdapterFactory.getReferenceLink(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479eed6aL, 0x5cf5c0d0479eed6bL, "config"), CollectionSequence.fromCollectionAndArray(new ArrayList<SNodeReference>(), SNodeOperations.getPointer(getRealNodeById("2539572119535275027")), SNodeOperations.getPointer(getRealNodeById("2539572119535275036")), SNodeOperations.getPointer(getRealNodeById("2539572119535275045")))).check();
      });
    }
    public void test_ScopeOf_FeatureModelConfigurationRef_config_2539572119535275225() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getRealNodeById("2539572119535275225");
        new CheckScopesAction(nodeToCheck, MetaAdapterFactory.getReferenceLink(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479eed6aL, 0x5cf5c0d0479eed6bL, "config"), CollectionSequence.fromCollectionAndArray(new ArrayList<SNodeReference>(), SNodeOperations.getPointer(getRealNodeById("2539572119535275036")), SNodeOperations.getPointer(getRealNodeById("2539572119535275045")))).check();
      });
    }

  }
}
