package test.org.iets3.variability.configuration.base.editor;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.junit.Assert;
import org.iets3.variability.configuration.base.intentions.IntentionUtilConfiguration;

@MPSLaunch
public class replaceWithUnsepcifiedConfigPreventedByInheritance2_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(replaceWithUnsepcifiedConfigPreventedByInheritance2_Test.class).projectPath(null).modelRef("r:c12bfe64-ecaf-4d6a-9f0c-0f5bfaf43528(test.org.iets3.variability.configuration.base.editor@tests)").reopenProject(null).build());

  public replaceWithUnsepcifiedConfigPreventedByInheritance2_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_mustNotBeApplicable() throws Throwable {
    new TestBody(this).test_mustNotBeApplicable();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    protected void initTestNodes() {
      prepareTestNodes("6963470238545388049");
    }

    public void test_mustNotBeApplicable() throws Exception {
      initTestNodes();
      runWithinCommand(() -> Assert.assertFalse(IntentionUtilConfiguration.isApplicableReplaceWithUnspecifiedConfig(getAnnotatedNode("n"))));
    }

  }
}
