package org.iets3.variability.base.ide.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconLoadingUtil;

public class IconContainer {
  protected static Icon ICON0 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_1030.png" : "TextIcon_1030.png"), IconContainer.class);
  protected static Icon ICON1 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_1010.png" : "TextIcon_1010.png"), IconContainer.class);
}
