package org.iets3.analysis.solversupport.util.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.MPSModuleRepository;
import java.util.Set;
import jetbrains.mps.smodel.MPSModuleOwner;
import java.util.Optional;
import jetbrains.mps.project.MPSProject;
import com.intellij.openapi.project.Project;
import jetbrains.mps.ide.project.ProjectHelper;
import jetbrains.mps.ide.MPSCoreComponents;
import jetbrains.mps.nodefs.MPSNodeVirtualFile;
import jetbrains.mps.nodefs.NodeVirtualFileSystem;
import com.intellij.openapi.project.ProjectLocator;
import java.util.List;
import com.intellij.openapi.application.ApplicationManager;
import jetbrains.mps.core.platform.Platform;
import jetbrains.mps.project.ProjectManager;
import java.util.Collections;
import org.jetbrains.mps.openapi.module.SModule;

public class ProjectUtil {
  /**
   * 
   * @deprecated 
   */
  @Deprecated
  public static SRepository projectRepositoryOld(SNode node) {
    SModel model = SNodeOperations.getModel(node);
    MPSModuleRepository repo = (MPSModuleRepository) (model.getRepository());
    Set<MPSModuleOwner> owners = repo.getOwners(model.getModule());
    Optional<MPSModuleOwner> mpsProject = owners.stream().filter((MPSModuleOwner mo) -> mo instanceof MPSProject).findFirst();

    assert mpsProject.isPresent() : "Could not find MPSProject";
    MPSProject project = (MPSProject) mpsProject.get();
    return project.getRepository();
  }

  public static Optional<Project> project(final SNode n) {
    return (Optional.ofNullable(ProjectUtil.currentProjectForNode(n)).map((p) -> ProjectHelper.toIdeaProject(p))).or(() -> Optional.ofNullable(projectFor(n))).or(() -> Optional.ofNullable(projectFor(SNodeOperations.asNode(SNodeOperations.getConcept(n)))));
  }

  public static Optional<SRepository> projectRepository(SNode n) {
    return project(n).map((p) -> ProjectHelper.getProjectRepository(p));
  }

  private static Project projectFor(SNode n) {
    MPSModuleRepository repo = MPSCoreComponents.getInstance().getPlatform().findComponent(MPSModuleRepository.class);
    MPSNodeVirtualFile file = NodeVirtualFileSystem.getInstance().getFileFor(repo, SNodeOperations.getContainingRoot(n));
    return ProjectLocator.getInstance().guessProjectForFile(file);
  }


  private static jetbrains.mps.project.Project currentProjectForNode(final SNode node) {
    final List<jetbrains.mps.project.Project> openedProjects = allOpenedProjects();
    jetbrains.mps.project.Project resolvedProject = Optional.ofNullable(SNodeOperations.getModel(node)).map((SModel m) -> projectFromModule(m, openedProjects)).orElseGet(() -> (openedProjects.isEmpty() ? null : openedProjects.get(0)));

    return resolvedProject;
  }

  private static List<jetbrains.mps.project.Project> allOpenedProjects() {
    MPSCoreComponents mcc = ApplicationManager.getApplication().getComponent(MPSCoreComponents.class);
    Platform platform = mcc.getPlatform();
    ProjectManager pm = platform.findComponent(ProjectManager.class);
    if (pm == null) {
      return Collections.emptyList();
    }
    return pm.getOpenedProjects();
  }

  private static jetbrains.mps.project.Project projectFromModule(SModel model, final List<jetbrains.mps.project.Project> openedProjects) {
    final SModule currentModule = model.getModule();
    return openedProjects.stream().filter((jetbrains.mps.project.Project p) -> p.isProjectModule(currentModule)).findFirst().orElseGet(() -> openedProjects.get(0));
  }

}
