package org.iets3.core.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.workbench.action.ActionAccess;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.ide.editor.MPSEditorDataKeys;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.iets3.core.base.behavior.ICanStoreCheckResult__BehaviorDescriptor;
import org.iets3.core.base.behavior.RunManuallyUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class clearResultsInModel_Action extends BaseAction {
  private static final Icon ICON = null;

  public clearResultsInModel_Action() {
    super("Clear Manual Check Results in Model", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setActionAccess(ActionAccess.UNDO_PROJECT);
    updateInBackground(true);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public boolean isApplicable(AnActionEvent event, final Map<String, Object> _params) {
    return !(RunManuallyBackgroundTask.isRunning());
  }
  @Override
  public void doUpdate(@NotNull AnActionEvent event, final Map<String, Object> _params) {
    this.setEnabledState(event.getPresentation(), this.isApplicable(event, _params));
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      SModel model = event.getData(MPSCommonDataKeys.CONTEXT_MODEL);
      MapSequence.fromMap(_params).put("model", model);
      if (model == null) {
        return false;
      }
    }
    {
      EditorContext p = event.getData(MPSEditorDataKeys.EDITOR_CONTEXT);
      MapSequence.fromMap(_params).put("ctx", p);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    List<SNode> stored = SModelOperations.nodes(((SModel) MapSequence.fromMap(_params).get("model")), CONCEPTS.ICanStoreCheckResult$bY);
    for (SNode s : ListSequence.fromList(stored)) {
      ICanStoreCheckResult__BehaviorDescriptor.deleteLastResult_id5yiuuzNYbce.invoke(s);
    }
    RunManuallyUtil.updateEditors(((EditorContext) MapSequence.fromMap(_params).get("ctx")), SNodeOperations.ofConcept(stored, CONCEPTS.ICanRunCheckManually$e));
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept ICanStoreCheckResult$bY = MetaAdapterFactory.getInterfaceConcept(0x7b68d745a7b848b9L, 0xbd9c05c0f8725a35L, 0x3dc39ae7decbd830L, "org.iets3.core.base.structure.ICanStoreCheckResult");
    /*package*/ static final SInterfaceConcept ICanRunCheckManually$e = MetaAdapterFactory.getInterfaceConcept(0x7b68d745a7b848b9L, 0xbd9c05c0f8725a35L, 0x3dc39ae7de59be3aL, "org.iets3.core.base.structure.ICanRunCheckManually");
  }
}
