package org.iets3.variability.featuremodel.base.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.ListScope;
import org.iets3.variability.featuremodel.base.behavior.IUsingParamContext__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class FMActualParam_Constraints extends BaseConstraintsDescriptor {
  /*package*/ FMActualParam_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.FMActualParam$O$, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.param$KiX, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:e8b70ecd-f70e-4568-8a91-fec86577fca7(org.iets3.variability.featuremodel.base.constraints)", "9038024733925238826");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          SNode fmi = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.FeatureModelInclude$Iq, true, false);
          return ListScope.forNamedElements(IUsingParamContext__BehaviorDescriptor.usingParams_idMYWxk17YoO.invoke(SLinkOperations.getTarget(fmi, LINKS.fm$EY24)));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FMActualParam$O$ = MetaAdapterFactory.getConcept(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x7d6d839c28c579b6L, "org.iets3.variability.featuremodel.base.structure.FMActualParam");
    /*package*/ static final SConcept FeatureModelInclude$Iq = MetaAdapterFactory.getConcept(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x375cadc475172168L, "org.iets3.variability.featuremodel.base.structure.FeatureModelInclude");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink param$KiX = MetaAdapterFactory.getReferenceLink(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x7d6d839c28c579b6L, 0x7d6d839c28c58576L, "param");
    /*package*/ static final SReferenceLink fm$EY24 = MetaAdapterFactory.getReferenceLink(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x375cadc475172168L, 0x375cadc475172169L, "fm");
  }
}
