package org.iets3.variability.configuration.base.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class fix_InvalidReferenceToFeature_QuickFix extends QuickFix_Runtime {
  public fix_InvalidReferenceToFeature_QuickFix() {
    super(new SNodePointer("r:791971f5-b094-4342-a75c-0ce6c1b43e9d(org.iets3.variability.configuration.base.typesystem)", "9159423170674957733"));
  }
  public String getDescription(SNode node) {
    return "Remove this " + ((String) fix_InvalidReferenceToFeature_QuickFix.this.getField("problem")[0]) + " to feature '" + SPropertyOperations.getString(SLinkOperations.getTarget(((SNode) fix_InvalidReferenceToFeature_QuickFix.this.getField("fc")[0]), LINKS.targetFeature$16lA), PROPS.name$MnvL) + "'";
  }
  public void execute(SNode node) {
    SNodeOperations.deleteNode(((SNode) fix_InvalidReferenceToFeature_QuickFix.this.getField("fc")[0]));
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink targetFeature$16lA = MetaAdapterFactory.getReferenceLink(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x302aa0c2ddab8940L, 0x5cf5c0d0479ec91eL, "targetFeature");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
