package org.iets3.core.expr.statemachines.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.iets3.core.expr.mutable.plugin.InteractionDescriptor;
import org.iets3.core.expr.mutable.plugin.InteractorValue;
import com.mbeddr.mpsutil.interpreter.rt.IContext;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.iets3.core.expr.statemachines.plugin.SmValue;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class StateMachine__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x7939418a3e285ca3L, "org.iets3.core.expr.statemachines.structure.StateMachine");

  public static final SMethod<Iterable<SNode>> events_id7$TgoCYjSsJ = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("events").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8735085014268479279L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2();
  public static final SMethod<Iterable<SNode>> queries_id4J6AqiIXbWG = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("queries").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5460220530822266668L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2();
  public static final SMethod<SNode> eventByName_id7bd8pkkAFT3 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("eventByName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8272305014728998467L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<Iterable<SNode>> variables_idaPhVmWXB8g = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("variables").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(195141004745404944L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2();
  public static final SMethod<SNode> variableByName_id7bd8pkk$zhp = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("variableByName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8272305014728438873L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<SNode> queryByName_id4J6AqiIYd94 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("queryByName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5460220530822533700L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<Iterable<SNode>> observableVariables_id33mFrum_2U2 = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("observableVariables").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3519191162853535362L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2();
  public static final SMethod<Iterable<SNode>> observableQueries_id4J6AqiIUUBX = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("observableQueries").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5460220530821671421L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2();
  public static final SMethod<Iterable<SNode>> getUniquelyNamedElements_id4qSf1u1TRfj = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("getUniquelyNamedElements").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5095889050031059923L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2();
  public static final SMethod<InteractionDescriptor> getDescriptor_id5y3VELft_Ye = new SMethodBuilder<InteractionDescriptor>(new SJavaCompoundTypeImpl(InteractionDescriptor.class)).name("getDescriptor").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6378203921121697678L).languageId(0x9c3b0b4469830440L, 0xfbba51185fc649ffL).build2();
  public static final SMethod<InteractorValue> createNewValue_id7WFhXJlVW$d = new SMethodBuilder<InteractorValue>(new SJavaCompoundTypeImpl(InteractorValue.class)).name("createNewValue").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(9163496876328077581L).languageId(0x9c3b0b4469830440L, 0xfbba51185fc649ffL).build2(SMethodBuilder.createJavaParameter(IContext.class, ""));
  public static final SMethod<Iterable<SNode>> visibleFunctions_idmQGcCvDdEN = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("visibleFunctions").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(411710798111759027L).languageId(0xa0548c072591085fL, 0x71934284d7d145eeL).build2();
  public static final SMethod<Iterable<SNode>> states_id3H4W4dizcin = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("states").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4270802518592504983L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2();
  public static final SMethod<Iterable<SNode>> allStates_idk9boAubCes = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("allStates").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(362871314067653532L).languageId(0xa0111e1c898de18eL, 0xcd87ddab6434448eL).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(events_id7$TgoCYjSsJ, queries_id4J6AqiIXbWG, eventByName_id7bd8pkkAFT3, variables_idaPhVmWXB8g, variableByName_id7bd8pkk$zhp, queryByName_id4J6AqiIYd94, observableVariables_id33mFrum_2U2, observableQueries_id4J6AqiIUUBX, getUniquelyNamedElements_id4qSf1u1TRfj, getDescriptor_id5y3VELft_Ye, createNewValue_id7WFhXJlVW$d, visibleFunctions_idmQGcCvDdEN, states_id3H4W4dizcin, allStates_idk9boAubCes);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static Iterable<SNode> events_id7$TgoCYjSsJ(@NotNull SNode __thisNode__) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys), CONCEPTS.Event$Q3);
  }
  /*package*/ static Iterable<SNode> queries_id4J6AqiIXbWG(@NotNull SNode __thisNode__) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys), CONCEPTS.StatemachineQuery$4e);
  }
  /*package*/ static SNode eventByName_id7bd8pkkAFT3(@NotNull SNode __thisNode__, final String name) {
    return Sequence.fromIterable(StateMachine__BehaviorDescriptor.events_id7$TgoCYjSsJ.invoke(__thisNode__)).findFirst((it) -> SPropertyOperations.getString(it, PROPS.name$MnvL).equals(name));
  }
  /*package*/ static Iterable<SNode> variables_idaPhVmWXB8g(@NotNull SNode __thisNode__) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys), CONCEPTS.StatemachineVar$Qb);
  }
  /*package*/ static SNode variableByName_id7bd8pkk$zhp(@NotNull SNode __thisNode__, final String name) {
    return Sequence.fromIterable(StateMachine__BehaviorDescriptor.variables_idaPhVmWXB8g.invoke(__thisNode__)).findFirst((it) -> SPropertyOperations.getString(it, PROPS.name$MnvL).equals(name));
  }
  /*package*/ static SNode queryByName_id4J6AqiIYd94(@NotNull SNode __thisNode__, final String name) {
    return Sequence.fromIterable(StateMachine__BehaviorDescriptor.queries_id4J6AqiIXbWG.invoke(__thisNode__)).findFirst((it) -> SPropertyOperations.getString(it, PROPS.name$MnvL).equals(name));
  }
  /*package*/ static Iterable<SNode> observableVariables_id33mFrum_2U2(@NotNull SNode __thisNode__) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys), CONCEPTS.StatemachineVar$Qb)).where((it) -> SPropertyOperations.getBoolean(it, PROPS.observable$wgmr));
  }
  /*package*/ static Iterable<SNode> observableQueries_id4J6AqiIUUBX(@NotNull SNode __thisNode__) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys), CONCEPTS.StatemachineQuery$4e)).where((it) -> SPropertyOperations.getBoolean(it, PROPS.observable$4F$u));
  }
  /*package*/ static Iterable<SNode> getUniquelyNamedElements_id4qSf1u1TRfj(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys)).union(ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.parameters$Z4bq)));
  }
  /*package*/ static InteractionDescriptor getDescriptor_id5y3VELft_Ye(@NotNull SNode __thisNode__) {
    return SmValue.descriptor(__thisNode__);
  }
  /*package*/ static InteractorValue createNewValue_id7WFhXJlVW$d(@NotNull SNode __thisNode__, IContext ctx) {
    return null;
  }
  /*package*/ static Iterable<SNode> visibleFunctions_idmQGcCvDdEN(@NotNull SNode __thisNode__) {
    return SLinkOperations.collect(SNodeOperations.ofConcept(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys), CONCEPTS.AbstractFunctionAdapter$Ob), LINKS.fun$NLoa);
  }
  /*package*/ static Iterable<SNode> states_id3H4W4dizcin(@NotNull SNode __thisNode__) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(__thisNode__, LINKS.contents$Pwys), CONCEPTS.State$OA);
  }
  /*package*/ static Iterable<SNode> allStates_idk9boAubCes(@NotNull SNode __thisNode__) {
    return SNodeOperations.getNodeDescendants(__thisNode__, CONCEPTS.State$OA, false, new SAbstractConcept[]{});
  }

  /*package*/ StateMachine__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Iterable<SNode>) events_id7$TgoCYjSsJ(node));
      case 1:
        return (T) ((Iterable<SNode>) queries_id4J6AqiIXbWG(node));
      case 2:
        return (T) ((SNode) eventByName_id7bd8pkkAFT3(node, (String) parameters[0]));
      case 3:
        return (T) ((Iterable<SNode>) variables_idaPhVmWXB8g(node));
      case 4:
        return (T) ((SNode) variableByName_id7bd8pkk$zhp(node, (String) parameters[0]));
      case 5:
        return (T) ((SNode) queryByName_id4J6AqiIYd94(node, (String) parameters[0]));
      case 6:
        return (T) ((Iterable<SNode>) observableVariables_id33mFrum_2U2(node));
      case 7:
        return (T) ((Iterable<SNode>) observableQueries_id4J6AqiIUUBX(node));
      case 8:
        return (T) ((Iterable<SNode>) getUniquelyNamedElements_id4qSf1u1TRfj(node));
      case 9:
        return (T) ((InteractionDescriptor) getDescriptor_id5y3VELft_Ye(node));
      case 10:
        return (T) ((InteractorValue) createNewValue_id7WFhXJlVW$d(node, (IContext) parameters[0]));
      case 11:
        return (T) ((Iterable<SNode>) visibleFunctions_idmQGcCvDdEN(node));
      case 12:
        return (T) ((Iterable<SNode>) states_id3H4W4dizcin(node));
      case 13:
        return (T) ((Iterable<SNode>) allStates_idk9boAubCes(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink contents$Pwys = MetaAdapterFactory.getContainmentLink(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x7939418a3e285ca3L, 0x7939418a3e4f9aabL, "contents");
    /*package*/ static final SContainmentLink parameters$Z4bq = MetaAdapterFactory.getContainmentLink(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x7939418a3e285ca3L, 0x56a4de6c1661d3L, "parameters");
    /*package*/ static final SContainmentLink fun$NLoa = MetaAdapterFactory.getContainmentLink(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x5b6b0ca1fa4e6b6L, 0x5b6b0ca1f838e57L, "fun");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Event$Q3 = MetaAdapterFactory.getConcept(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x7939418a3e285cdaL, "org.iets3.core.expr.statemachines.structure.Event");
    /*package*/ static final SConcept StatemachineQuery$4e = MetaAdapterFactory.getConcept(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x4bc699a4aee114fbL, "org.iets3.core.expr.statemachines.structure.StatemachineQuery");
    /*package*/ static final SConcept StatemachineVar$Qb = MetaAdapterFactory.getConcept(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x2b547b5bce0e114L, "org.iets3.core.expr.statemachines.structure.StatemachineVar");
    /*package*/ static final SConcept AbstractFunctionAdapter$Ob = MetaAdapterFactory.getConcept(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x5b6b0ca1fa4e6b6L, "org.iets3.core.expr.toplevel.structure.AbstractFunctionAdapter");
    /*package*/ static final SConcept State$OA = MetaAdapterFactory.getConcept(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x7939418a3e285cd7L, "org.iets3.core.expr.statemachines.structure.State");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty observable$wgmr = MetaAdapterFactory.getProperty(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x2b547b5bce0e114L, 0x30d6adb796942bf5L, "observable");
    /*package*/ static final SProperty observable$4F$u = MetaAdapterFactory.getProperty(0xcd87ddab6434448eL, 0xa0111e1c898de18eL, 0x4bc699a4aee114fbL, 0x30d6adb796942bf5L, "observable");
  }
}
