package org.iets3.core.expr.tracing.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.iets3.core.expr.tracing.util.TracingValue;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import com.mbeddr.mpsutil.framecell.runtime.FrameCell;
import java.awt.Color;
import jetbrains.mps.nodeEditor.cells.EditorCell_Property;
import jetbrains.mps.nodeEditor.cells.ModelAccessor;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.EmptyCellAction;
import jetbrains.mps.editor.runtime.style.CellAlign;
import jetbrains.mps.nodeEditor.EditorSettings;
import com.intellij.ui.JBColor;

/*package*/ class BaseConcept_IETS3Tracing_conditionalEditor_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public BaseConcept_IETS3Tracing_conditionalEditor_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createPriorityInfoCell_1();
  }

  private EditorCell createPriorityInfoCell_0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = null;
    editorCell = createAlternation_0();
    editorCell.setBig(true);
    setCellContext(editorCell);
    return editorCell;
  }
  private EditorCell createPriorityInfoCell_1() {
    return createPriorityInfoCell_0(getEditorContext(), myNode);
  }
  private EditorCell createAlternation_0() {
    boolean alternationCondition = true;
    alternationCondition = nodeCondition_z39m8j_a0a();
    EditorCell editorCell = null;
    if (alternationCondition) {
      editorCell = createAlternation_1();
    } else {
      editorCell = createNextEditor_2();
    }
    return editorCell;
  }
  private boolean nodeCondition_z39m8j_a0a() {
    TracingValue tv = TracingValue.get(myNode);
    return tv != null;
  }
  private EditorCell createAlternation_1() {
    boolean alternationCondition = true;
    alternationCondition = nodeCondition_z39m8j_a0a0();
    EditorCell editorCell = null;
    if (alternationCondition) {
      editorCell = createCollection_0();
    } else {
      editorCell = createCollection_2();
    }
    return editorCell;
  }
  private boolean nodeCondition_z39m8j_a0a0() {
    // true -> vertical layout, false -> horizontal layout
    return ListSequence.fromList(SNodeOperations.getChildren(myNode)).isNotEmpty();
  }
  private EditorCell createCollection_0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_z39m8j_a0a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.BASE_LINE_CELL, true);
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createFrameCell_1());
    editorCell.addEditorCell(createReadOnlyModelAccessor_0());
    return editorCell;
  }
  private EditorCell createCollection_1() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_z39m8j_a0a0a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.BASE_LINE_CELL, true);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createNextEditor_0());
    return editorCell;
  }
  private EditorCell createNextEditor_0() {
    {
      EditorCell editorCell = getCellFactory().createEditorCell(myNode, false, BaseConcept_IETS3Tracing_conditionalEditor_Editor_Tracing.class);
      return editorCell;
    }
  }
  private EditorCell createFrameCell_0(final EditorContext editorContext, final SNode node) {
    FrameCell editorCell = new FrameCell(editorContext, node);
    editorCell.setCellId("FrameCell_z39m8j_a0a0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.BACKGROUND_COLOR, getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_z39m8j_a0a0a0a()));
    style.set(StyleAttributes.getInstance().<Color>getAttribute("com.mbeddr.mpsutil.framecell", "frame-color"), _StyleParameter_QueryFunction_z39m8j_a1a0a0a());
    style.set(StyleAttributes.getInstance().<Integer>getAttribute("com.mbeddr.mpsutil.framecell", "frame-padding"), _StyleParameter_QueryFunction_z39m8j_a2a0a0a());
    style.set(StyleAttributes.getInstance().<Integer>getAttribute("com.mbeddr.mpsutil.framecell", "frame-width"), _StyleParameter_QueryFunction_z39m8j_a3a0a0a());
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createCollection_1());
    return editorCell;
  }
  private EditorCell createFrameCell_1() {
    return createFrameCell_0(getEditorContext(), myNode);
  }
  private Color _StyleParameter_QueryFunction_z39m8j_a0a0a0a() {
    return BoxColors.getBrightColor(getNode());
  }
  private Color _StyleParameter_QueryFunction_z39m8j_a1a0a0a() {
    return BoxColors.getDarkColor(getNode());
  }
  private int _StyleParameter_QueryFunction_z39m8j_a2a0a0a() {
    return 2;
  }
  private int _StyleParameter_QueryFunction_z39m8j_a3a0a0a() {
    return 2;
  }
  private EditorCell createReadOnlyModelAccessor_0() {
    EditorCell_Property editorCell = EditorCell_Property.create(getEditorContext(), new ModelAccessor.ReadOnly() {
      public String getText() {
        String v = TracingValue.get(myNode).renderedValue;
        if (v.startsWith("FAIL:")) {
          return " \u21EA " + v;
        }
        return " \u21D2 " + v;
      }
    }, myNode);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ReadOnlyModelAccessor_z39m8j_b0a0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.BACKGROUND_COLOR, getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_z39m8j_a0b0a0a()));
    style.set(StyleAttributes.HORIZONTAL_ALIGN, CellAlign.RIGHT);
    style.set(StyleAttributes.EDITABLE, false);
    style.set(StyleAttributes.FONT_SIZE, _StyleParameter_QueryFunction_z39m8j_a3b0a0a());
    style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_z39m8j_a4b0a0a()));
    editorCell.getStyle().putAll(style);
    ClickValue.setCellActions(editorCell, myNode, getEditorContext());
    return editorCell;
  }
  private Color _StyleParameter_QueryFunction_z39m8j_a0b0a0a() {
    return BoxColors.getDarkColor(getNode());
  }
  private int _StyleParameter_QueryFunction_z39m8j_a3b0a0a() {
    double f = 0.75;
    return ((int) (EditorSettings.getInstance().getFontSize() * f));
  }
  private Color _StyleParameter_QueryFunction_z39m8j_a4b0a0a() {
    return new JBColor(Color.white, Color.black);
  }
  private EditorCell createCollection_2() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_z39m8j_a0a0_0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.BASE_LINE_CELL, true);
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createCollection_3());
    editorCell.addEditorCell(createReadOnlyModelAccessor_1());
    return editorCell;
  }
  private EditorCell createCollection_3() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_z39m8j_a0a0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.BASE_LINE_CELL, true);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createNextEditor_1());
    return editorCell;
  }
  private EditorCell createNextEditor_1() {
    {
      EditorCell editorCell = getCellFactory().createEditorCell(myNode, false, BaseConcept_IETS3Tracing_conditionalEditor_Editor_Tracing.class);
      return editorCell;
    }
  }
  private EditorCell createReadOnlyModelAccessor_1() {
    EditorCell_Property editorCell = EditorCell_Property.create(getEditorContext(), new ModelAccessor.ReadOnly() {
      public String getText() {
        String v = TracingValue.get(myNode).renderedValue;
        if (v.startsWith("FAIL:")) {
          return " \u21EA " + v;
        }
        return "\u21D2 " + v + " ";
      }
    }, myNode);
    editorCell.setAction(CellActionType.DELETE, EmptyCellAction.getInstance());
    editorCell.setAction(CellActionType.BACKSPACE, EmptyCellAction.getInstance());
    editorCell.setCellId("ReadOnlyModelAccessor_z39m8j_b0a0a_0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.BACKGROUND_COLOR, getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_z39m8j_a0b0a0a_0()));
    style.set(StyleAttributes.EDITABLE, false);
    style.set(StyleAttributes.FONT_SIZE, _StyleParameter_QueryFunction_z39m8j_a2b0a0a());
    style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_z39m8j_a3b0a0a_0()));
    editorCell.getStyle().putAll(style);
    ClickValue.setCellActions(editorCell, myNode, getEditorContext());
    return editorCell;
  }
  private Color _StyleParameter_QueryFunction_z39m8j_a0b0a0a_0() {
    return new JBColor(Color.black, Color.white);
  }
  private int _StyleParameter_QueryFunction_z39m8j_a2b0a0a() {
    double f = 0.75;
    return ((int) (EditorSettings.getInstance().getFontSize() * f));
  }
  private Color _StyleParameter_QueryFunction_z39m8j_a3b0a0a_0() {
    return new JBColor(Color.white, Color.black);
  }
  private EditorCell createNextEditor_2() {
    {
      EditorCell editorCell = getCellFactory().createEditorCell(myNode, false, BaseConcept_IETS3Tracing_conditionalEditor_Editor_Tracing.class);
      return editorCell;
    }
  }
}
