package org.iets3.components.core.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;
import org.iets3.components.core.behavior.AbstractPortToPortConnector__BehaviorDescriptor;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class typeof_AbstractPortToPortConnector_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_AbstractPortToPortConnector_InferenceRule() {
  }
  public void applyRule(final SNode aptpc, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    final SNode connection_typevar_3864571482956970146 = typeCheckingContext.createNewRuntimeTypesVariable();
    final Tuples._2<SNode, SNode> ports = AbstractPortToPortConnector__BehaviorDescriptor.getPorts_idmIQkxg5ZT6.invoke(aptpc);

    // to get a sane error message on the check for the user we have to wait until both types are solved
    {
      final SNode left = typeCheckingContext.typeOf(ports._0(), "r:769eaa92-d4cb-4fa9-87e4-269f7f35a1eb(org.iets3.components.core.typesystem)", "3864571482956970158", true);
      typeCheckingContext.whenConcrete(left, () -> {
        {
          final SNode right = typeCheckingContext.typeOf(ports._1(), "r:769eaa92-d4cb-4fa9-87e4-269f7f35a1eb(org.iets3.components.core.typesystem)", "3864571482956970166", true);
          typeCheckingContext.whenConcrete(right, () -> {
            if (!(typeCheckingContext.isSingleTypeComputation())) {
              {
                SNode _nodeToCheck_1029348928467 = aptpc;
                EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, ConnectorErrorMsgHelper.getConnectorErrMsg(typeCheckingContext.getExpandedNode(left), typeCheckingContext.getExpandedNode(right)), "r:769eaa92-d4cb-4fa9-87e4-269f7f35a1eb(org.iets3.components.core.typesystem)", "3864571482956970173", 0, null);
                typeCheckingContext.createEquation((SNode) typeCheckingContext.getExpandedNode(right), (SNode) typeCheckingContext.getExpandedNode(left), true, _info_12389875345);
              }
            }
          }, "r:769eaa92-d4cb-4fa9-87e4-269f7f35a1eb(org.iets3.components.core.typesystem)", "3864571482958003298", false, false);
        }
      }, "r:769eaa92-d4cb-4fa9-87e4-269f7f35a1eb(org.iets3.components.core.typesystem)", "3864571482958001544", false, false);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.AbstractPortToPortConnector$JI;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractPortToPortConnector$JI = MetaAdapterFactory.getConcept(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x5aed9485017fe26L, "org.iets3.components.core.structure.AbstractPortToPortConnector");
  }
}
