package org.iets3.variability.configuration.base.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import jetbrains.mps.openapi.editor.descriptor.EditorHintsProvider;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorHint;
import java.util.Arrays;
import jetbrains.mps.editor.runtime.descriptor.ConceptEditorHintImpl;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.TransformationMenu;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.openapi.editor.descriptor.NamedMenuId;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase implements EditorHintsProvider {
  private Collection<ConceptEditorHint> myHints = Arrays.<ConceptEditorHint>asList(new ConceptEditorHintImpl("tooltipHint_kzhlkm_a0", "", false, "org.iets3.variability.configuration.base.editor.GeneratedHints.tooltipHint_kzhlkm_a0"));
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ExtendedFeatureModelConfigurationRef_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new FMCInheritanceCheck_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new FMConfigActualParam_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new FeatureAttributeAssignment_Editor());
      case 4:
        return Arrays.asList(new ConceptEditor[]{new FeatureConfiguration_Editor(), new FeatureConfiguration_tooltipHint_kzhlkm_a0_Editor()});
      case 5:
        return Collections.<ConceptEditor>singletonList(new FeatureConfigurationErrorContent_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new FeatureModelConfiguration_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new FeatureModelConfigurationBase_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new FeatureModelConfigurationRef_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new FeatureWithCardinalityConfiguration_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new InlineFeatureConfigurationContent_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  private Collection<ConceptEditorComponent> getDeclaredEC_0(String editorComponentId) {
    if ("org.iets3.variability.configuration.base.editor.DummyForGrammarCells".equals(editorComponentId)) {
      return Collections.singletonList(new DummyForGrammarCells());
    }
    return Collections.emptyList();
  }
  private Collection<ConceptEditorComponent> getDeclaredEC_1(String editorComponentId) {
    if ("org.iets3.variability.configuration.base.editor.AssignmentCauseEditor".equals(editorComponentId)) {
      return Collections.singletonList(new AssignmentCauseEditor());
    }
    return Collections.emptyList();
  }
  @NotNull
  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return getDeclaredEC_0(editorComponentId);
      case 1:
        return getDeclaredEC_1(editorComponentId);
      default:
    }
    return Collections.emptyList();
  }

  public Collection<ConceptEditorHint> getHints() {
    return myHints;
  }

  @NotNull
  @Override
  public Collection<TransformationMenu> getDeclaredDefaultTransformationMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex2.index(cncpt)) {
      case 0:
        return Arrays.asList(new TransformationMenu[]{new IncludeBeforeAfterTransformations(), new template_GrammarCellsSideTransformationsMenu()});
      default:
    }
    return Collections.<TransformationMenu>emptyList();
  }
  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex3.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new GrammarCellsSubstituteMenu_AbstractFeatureConfiguration());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new GrammarCellsSubstituteMenu_AbstractFeatureConfigurationContent());
      case 2:
        return Arrays.asList(new SubstituteMenu[]{new ExtendedFeatureModelConfigurationRef_SubstituteMenu(), new GrammarCellsSubstituteMenu_ExtendedFeatureModelConfigurationRef()});
      case 3:
        return Collections.<SubstituteMenu>singletonList(new GrammarCellsSubstituteMenu_FMCInheritanceCheck());
      case 4:
        return Collections.<SubstituteMenu>singletonList(new GrammarCellsSubstituteMenu_FMConfigActualParam());
      case 5:
        return Arrays.asList(new SubstituteMenu[]{new FeatureAttributeAssignment_SubstituteMenu(), new GrammarCellsSubstituteMenu_FeatureAttributeAssignment()});
      case 6:
        return Arrays.asList(new SubstituteMenu[]{new FeatureConfiguration_SubstituteMenu(), new GrammarCellsSubstituteMenu_FeatureConfiguration()});
      case 7:
        return Collections.<SubstituteMenu>singletonList(new GrammarCellsSubstituteMenu_FeatureConfigurationErrorContent());
      case 8:
        return Arrays.asList(new SubstituteMenu[]{new FeatureModelConfiguration_SubstituteMenu(), new GrammarCellsSubstituteMenu_FeatureModelConfiguration()});
      case 9:
        return Collections.<SubstituteMenu>singletonList(new GrammarCellsSubstituteMenu_FeatureModelConfigurationBase());
      case 10:
        return Arrays.asList(new SubstituteMenu[]{new FeatureModelConfigurationRef_SubstituteMenu(), new GrammarCellsSubstituteMenu_FeatureModelConfigurationRef()});
      case 11:
        return Arrays.asList(new SubstituteMenu[]{new FeatureWithCardinalityConfiguration_SubstituteMenu(), new GrammarCellsSubstituteMenu_FeatureWithCardinalityConfiguration()});
      case 12:
        return Collections.<SubstituteMenu>singletonList(new GrammarCellsSubstituteMenu_InlineFeatureConfigurationContent());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }
  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredNamedSubstituteMenus(NamedMenuId menuId) {
    SAbstractConcept cncpt = (SAbstractConcept) menuId.getConcept();
    switch (conceptIndex4.index(cncpt)) {
      case 0:
        if (true) {
          switch (menuId.getFqName()) {
            case "org.iets3.variability.configuration.base.editor.FeatureModelConfiguration_SmartReference":
              return Arrays.asList(new SubstituteMenu[]{new FeatureModelConfiguration_SmartReference()});
            default:
          }
        }
        break;
      default:
    }

    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x4617323a864bd036L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x32699b8ea1ed143bL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x7d6d839c2865b139L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x302aa0c2ddc5ae16L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479ec91dL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x34aae17cd64425dbL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479ec915L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x2e34d227ff954d8bL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479eed6aL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x55c09a0155d9c97cL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479f4bfcL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x302aa0c2ddc5ae16L)).seal();
  private static final ConceptSwitchIndex conceptIndex2 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).seal();
  private static final ConceptSwitchIndex conceptIndex3 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x302aa0c2ddab8940L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479ec950L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x4617323a864bd036L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x32699b8ea1ed143bL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x7d6d839c2865b139L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x302aa0c2ddc5ae16L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479ec91dL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x34aae17cd64425dbL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479ec915L), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x2e34d227ff954d8bL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479eed6aL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x55c09a0155d9c97cL), MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479f4bfcL)).seal();
  private static final ConceptSwitchIndex conceptIndex4 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x71226ee2bbc445d2L, 0xa41d20b97237156cL, 0x5cf5c0d0479ec915L)).seal();
}
