package org.iets3.variability.featuremodel.base.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class FeatureAttribute_SubstituteMenu extends SubstituteMenuBase {
  public FeatureAttribute_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "FeatureAttribute", new SNodePointer("r:6f04f8d5-318b-477f-9c0e-932f665e2395(org.iets3.variability.featuremodel.base.editor)", "6549841121312151492")));
  }

}
