package org.iets3.variability.featuremodel.base.editor;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.iets3.variability.featuremodel.base.behavior.FeatureTreeNode__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.iets3.variability.featuremodel.base.behavior.AbstractFeature__BehaviorDescriptor;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class TopPartFeatureUtil {

  public static boolean isApplicable(SNode feature) {
    return !((boolean) FeatureTreeNode__BehaviorDescriptor.isRoot_id7Nu9WvXvoDo.invoke(feature)) && Sequence.fromIterable(AbstractFeature__BehaviorDescriptor.subFeatures_id6GZHy357BW_.invoke(feature)).isEmpty();
  }

  public static SNode execute(SNode ftn) {
    SNode fi = SNodeFactoryOperations.replaceWithNewChild(ftn, CONCEPTS.FeatureModelInclude$Iq);
    SPropertyOperations.assign(fi, PROPS.name$MnvL, SPropertyOperations.getString(ftn, PROPS.name$MnvL));
    SLinkOperations.setTarget(fi, LINKS.cardinality$EsDt, SLinkOperations.getTarget(ftn, LINKS.cardinality$EsDt));
    return fi;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FeatureModelInclude$Iq = MetaAdapterFactory.getConcept(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x375cadc475172168L, "org.iets3.variability.featuremodel.base.structure.FeatureModelInclude");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink cardinality$EsDt = MetaAdapterFactory.getContainmentLink(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x375cadc475172167L, 0x375cadc47519250cL, "cardinality");
  }
}
