package org.iets3.variability.featuremodel.base.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class UsingParamRefDotTarget_SubstituteMenu extends SubstituteMenuBase {
  public UsingParamRefDotTarget_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for UsingParamRefDotTarget. Generated from implicit smart reference attribute.", new SNodePointer("r:a7e2f963-3e46-49e0-a385-e8c7f33c91b7(org.iets3.variability.featuremodel.base.structure)", "2826783127491503163")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_6rnbms_a(), CONCEPTS.UsingParamRefDotTarget$Xh));
    result.add(new SMP_Subconcepts_6rnbms_b());
    return result;
  }

  public class SMP_ReferenceScope_6rnbms_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_6rnbms_a() {
      super(CONCEPTS.UsingParamRefDotTarget$Xh, LINKS.param$Rgt8, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_6rnbms_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_6rnbms_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "UsingParamRefDotTarget", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.UsingParamRefDotTarget$Xh);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept UsingParamRefDotTarget$Xh = MetaAdapterFactory.getConcept(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x273ac0470b32e43bL, "org.iets3.variability.featuremodel.base.structure.UsingParamRefDotTarget");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink param$Rgt8 = MetaAdapterFactory.getReferenceLink(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x273ac0470b32e43bL, 0x273ac0470b32ef6cL, "param");
  }
}
