package org.iets3.variability.featuremodel.base.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import org.iets3.variability.featuremodel.base.behavior.ICanBeCheckStateInitalized__BehaviorDescriptor;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.openapi.intentions.ParameterizedIntentionExecutable;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;

public final class stateInitalization_Intention extends AbstractIntentionDescriptor implements IntentionFactory {

  public stateInitalization_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:f668c7dc-a067-4444-b4cb-762be58b0141(org.iets3.variability.featuremodel.base.intentions)", "1959700701261608474"));
  }

  @Override
  public String getPresentation() {
    return "stateInitalization";
  }

  @Override
  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    List<IntentionExecutable> list = ListSequence.fromList(new ArrayList<IntentionExecutable>());
    List<String> paramList = parameter(node, context);
    if (paramList != null) {
      for (String param : paramList) {
        ListSequence.fromList(list).addElement(new IntentionImplementation(param));
      }
    }
    return list;
  }
  private List<String> parameter(final SNode node, final EditorContext editorContext) {
    List<String> options = new ArrayList<String>();
    if (!(SEnumOperations.isMember(ICanBeCheckStateInitalized__BehaviorDescriptor.defaultFeatureSelectionState_id1GMgmu$U9$5.invoke(node), 0x74046bf8564f89faL))) {
      options.add("Remove Initial State");
    }
    if (!(SEnumOperations.isMember(ICanBeCheckStateInitalized__BehaviorDescriptor.defaultFeatureSelectionState_id1GMgmu$U9$5.invoke(node), 0x74046bf8564f89fbL))) {
      options.add("Set Initially Checked");
    }
    if (!(SEnumOperations.isMember(ICanBeCheckStateInitalized__BehaviorDescriptor.defaultFeatureSelectionState_id1GMgmu$U9$5.invoke(node), 0x74046bf85651daf6L))) {
      options.add("Set Initially Unchecked");
    }
    return options;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable implements ParameterizedIntentionExecutable {
    private String myParameter;
    public IntentionImplementation(String parameter) {
      myParameter = parameter;
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "VARIABILITY: " + (myParameter);
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      if (myParameter.contains("Remove")) {
        ICanBeCheckStateInitalized__BehaviorDescriptor.setDefaultCheckState_id1GMgmu$Up$S.invoke(node, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x74046bf8564f89f9L, "org.iets3.variability.featuremodel.base.structure.DefaultCheckedState"), 0x74046bf8564f89faL, "untouched"));
      }
      if (myParameter.contains("Unchecked")) {
        ICanBeCheckStateInitalized__BehaviorDescriptor.setDefaultCheckState_id1GMgmu$Up$S.invoke(node, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x74046bf8564f89f9L, "org.iets3.variability.featuremodel.base.structure.DefaultCheckedState"), 0x74046bf85651daf6L, "unchecked"));
      }
      if (myParameter.contains("Checked")) {
        ICanBeCheckStateInitalized__BehaviorDescriptor.setDefaultCheckState_id1GMgmu$Up$S.invoke(node, SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x74046bf8564f89f9L, "org.iets3.variability.featuremodel.base.structure.DefaultCheckedState"), 0x74046bf8564f89fbL, "checked"));
      }

    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      if (!(isApplicableToNode(node, editorContext))) {
        return false;
      }
      return true;
    }

    private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
      return (boolean) ICanBeCheckStateInitalized__BehaviorDescriptor.isFeatureSelectionStateInitializable_id1GMgmu$HZYe.invoke(node);
    }


    @Override
    public IntentionDescriptor getDescriptor() {
      return stateInitalization_Intention.this;
    }

    public Object getParameter() {
      return myParameter;
    }
  }
}
