package org.iets3.core.expr.toplevel.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class BuilderExpression__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x465d5f01132dafd3L, "org.iets3.core.expr.toplevel.structure.BuilderExpression");

  public static final SMethod<Void> addMissingSetters_id4ptnK4jexBh = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("addMissingSetters").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5070313213711227345L).languageId(0xa0548c072591085fL, 0x71934284d7d145eeL).build2();
  public static final SMethod<String> renderReadable_id4Y0vh0cfqjE = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("renderReadable").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5728716233893586154L).languageId(0xb66a309a6e1a7290L, 0xcfaa4966b7d54b69L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(addMissingSetters_id4ptnK4jexBh, renderReadable_id4Y0vh0cfqjE);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static void addMissingSetters_id4ptnK4jexBh(@NotNull SNode __thisNode__) {
    for (SNode f : Sequence.fromIterable(BuilderAdapter__BehaviorDescriptor.missingSetters_id4ptnK4jbJRO.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.adapted$goB5)))) {
      ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.elements$iY16)).addElement(createFieldSetter_nk9e8v_a0a0a0a0(f));
    }
  }
  /*package*/ static String renderReadable_id4Y0vh0cfqjE(@NotNull SNode __thisNode__) {
    return "build" + ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.elements$iY16)).select((it) -> (String) BuilderElement__BehaviorDescriptor.renderReadable_id7S4tmubD2lA.invoke(it));
  }

  /*package*/ BuilderExpression__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        addMissingSetters_id4ptnK4jexBh(node);
        return null;
      case 1:
        return (T) ((String) renderReadable_id4Y0vh0cfqjE(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
  private static SNode createFieldSetter_nk9e8v_a0a0a0a0(SNode p0) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.FieldSetter$nv);
    n0.forChild(LINKS.value$jc3B).init(CONCEPTS.Expression$D_);
    n0.setReferenceTarget(LINKS.field$jb__, p0);
    return n0.getResult();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink elements$iY16 = MetaAdapterFactory.getContainmentLink(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x465d5f01132dafd3L, 0x465d5f01132dafe9L, "elements");
    /*package*/ static final SContainmentLink adapted$goB5 = MetaAdapterFactory.getContainmentLink(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x465d5f01132dafd3L, 0x465d5f01132dafddL, "adapted");
    /*package*/ static final SContainmentLink value$jc3B = MetaAdapterFactory.getContainmentLink(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x465d5f01132dafecL, 0x465d5f01132daff8L, "value");
    /*package*/ static final SReferenceLink field$jb__ = MetaAdapterFactory.getReferenceLink(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x465d5f01132dafecL, 0x465d5f01132daff6L, "field");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FieldSetter$nv = MetaAdapterFactory.getConcept(0x71934284d7d145eeL, 0xa0548c072591085fL, 0x465d5f01132dafecL, "org.iets3.core.expr.toplevel.structure.FieldSetter");
    /*package*/ static final SConcept Expression$D_ = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x670d5e92f854a047L, "org.iets3.core.expr.base.structure.Expression");
  }
}
