package org.iets3.core.expr.typetags.physunits.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

/**
 * 
 */
public class ConversionHelper {

  public static SNode makeConvertToTarget(SNode expr, SNode targetUnit, SNode context) {
    // As the ConvertToTarget node might access its context, we need to generate a surrounding dot expression.
    return SNodeOperations.as(check_5foaiq_a0b0b(makeConvertDotExpr(expr, targetUnit, context)), CONCEPTS.ConvertToTarget$M7);
  }

  public static SNode makeConvertDotExpr(SNode expr, SNode targetUnit, SNode context) {
    {
      final SNode unitRef = targetUnit;
      if (SNodeOperations.isInstanceOf(unitRef, CONCEPTS.UnitReference$Zo)) {
        return makeDotExprAux(expr, unitRef, context);
      }
    }
    {
      final SNode unit = targetUnit;
      if (SNodeOperations.isInstanceOf(unit, CONCEPTS.IUnit$tw)) {
        return makeDotExprAux(expr, createUnitReference_5foaiq_b0a0b0d(unit), context);
      }
    }
    return null;
  }

  private static SNode makeDotExprAux(SNode expr, SNode targetUnitRef, SNode context) {
    SNode ctt = createConvertToTarget_5foaiq_a0a0f(targetUnitRef);

    // The resulting DotExpression will not have any ancestors, but the ConvertToTarget node might
    // need to access the ancestor<IVisibleElementProvider> for scoping.
    IConvertUnit__BehaviorDescriptor.setFallbackVisibleElementProvider_idTizm$fGBF2.invoke(ctt, context);

    SNode result = createDotExpression_5foaiq_a0g0f(expr, ctt);
    return result;
  }
  private static SNode check_5foaiq_a0b0b(SNode checkedDotOperand) {
    if (null != checkedDotOperand) {
      return SLinkOperations.getTarget(checkedDotOperand, LINKS.target$u23F);
    }
    return null;
  }
  private static SNode createUnitReference_5foaiq_b0a0b0d(SNode p0) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.UnitReference$Zo);
    n0.setReferenceTarget(LINKS.unit$nTeG, p0);
    return n0.getResult();
  }
  private static SNode createConvertToTarget_5foaiq_a0a0f(SNode p0) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.ConvertToTarget$M7);
    n0.forChild(LINKS.targetUnit$_yUk).initNode(p0, CONCEPTS.UnitReference$Zo, true);
    return n0.getResult();
  }
  private static SNode createDotExpression_5foaiq_a0g0f(SNode p0, SNode p1) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.DotExpression$jp);
    n0.forChild(LINKS.expr$CW3E).initNode(p0, CONCEPTS.Expression$D_, true);
    n0.forChild(LINKS.target$u23F).initNode(p1, CONCEPTS.IDotTarget$jS, true);
    return n0.getResult();
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ConvertToTarget$M7 = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x7e22431b94d6fd64L, "org.iets3.core.expr.typetags.physunits.structure.ConvertToTarget");
    /*package*/ static final SConcept UnitReference$Zo = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d4dc5L, "org.iets3.core.expr.typetags.physunits.structure.UnitReference");
    /*package*/ static final SInterfaceConcept IUnit$tw = MetaAdapterFactory.getInterfaceConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d40ceL, "org.iets3.core.expr.typetags.physunits.structure.IUnit");
    /*package*/ static final SConcept DotExpression$jp = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x7cef88020a0f4249L, "org.iets3.core.expr.base.structure.DotExpression");
    /*package*/ static final SConcept Expression$D_ = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x670d5e92f854a047L, "org.iets3.core.expr.base.structure.Expression");
    /*package*/ static final SInterfaceConcept IDotTarget$jS = MetaAdapterFactory.getInterfaceConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x7cef88020a0f424aL, "org.iets3.core.expr.base.structure.IDotTarget");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink target$u23F = MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x7cef88020a0f4249L, 0x7cef88020a0f424bL, "target");
    /*package*/ static final SReferenceLink unit$nTeG = MetaAdapterFactory.getReferenceLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d4dc5L, 0x73b48a125b0daafcL, "unit");
    /*package*/ static final SContainmentLink targetUnit$_yUk = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x7e22431b94d6fd64L, 0x33aa6489a920a49cL, "targetUnit");
    /*package*/ static final SContainmentLink expr$CW3E = MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x3b256bb6ae8048d8L, 0x3b256bb6ae8048d9L, "expr");
  }
}
