package org.iets3.components.hardware.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import com.mbeddr.core.base.behavior.AbstractTreeViewNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import com.mbeddr.core.base.behavior.NodeTreeViewNode;
import org.iets3.components.core.behavior.AbstractConnectorBase__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public final class WireConnector__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xc35abfa80db04d42L, 0xbb3ff46112aeb888L, 0x2fd25306d6b99d15L, "org.iets3.components.hardware.structure.WireConnector");

  public static final SMethod<AbstractTreeViewNode> getTreeNode_id7NyyyjNtbn2 = new SMethodBuilder<AbstractTreeViewNode>(new SJavaCompoundTypeImpl(AbstractTreeViewNode.class)).name("getTreeNode").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8998906896747640258L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<SNode> kind_id6LfBX8Yl7Hz = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("kind").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7804632404594031459L).languageId(0xb6713d118449c6e7L, 0xf0fd486f857743e9L).build2();
  public static final SMethod<SNode> getTypedContextNode_id4fgA7QrKR89 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getTypedContextNode").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4886573260948599305L).languageId(0xb66a309a6e1a7290L, 0xcfaa4966b7d54b69L).build2();
  public static final SMethod<String> treeViewLabel_id7Atos1ybm9U = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("treeViewLabel").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8763267928841609850L).languageId(0xb6713d118449c6e7L, 0xf0fd486f857743e9L).build2();
  public static final SMethod<SNode> getGoverningPort_idmIQkxg5V$2 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getGoverningPort").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(409503520741898498L).languageId(0xb6713d118449c6e7L, 0xf0fd486f857743e9L).build2();
  public static final SMethod<SNode> getTarget_id3E8pWteyf_5 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getTarget").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4217735156746221893L).languageId(0xb6713d118449c6e7L, 0xf0fd486f857743e9L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getTreeNode_id7NyyyjNtbn2, kind_id6LfBX8Yl7Hz, getTypedContextNode_id4fgA7QrKR89, treeViewLabel_id7Atos1ybm9U, getGoverningPort_idmIQkxg5V$2, getTarget_id3E8pWteyf_5);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static AbstractTreeViewNode getTreeNode_id7NyyyjNtbn2(@NotNull SNode __thisNode__, final String cat) {
    return new NodeTreeViewNode(__thisNode__, AbstractConnectorBase__BehaviorDescriptor.treeViewLabel_id7Atos1ybm9U.invoke(__thisNode__), cat, new String[]{"structure"}) {
      public int getChildCountFromModel() {
        return 0;
      }
      public List<AbstractTreeViewNode> getChildrenFromModel() {
        return null;
      }
    };
  }
  /*package*/ static SNode kind_id6LfBX8Yl7Hz(@NotNull SNode __thisNode__) {
    return createHardwareKind_opimz8_a0a1();
  }
  /*package*/ static SNode getTypedContextNode_id4fgA7QrKR89(@NotNull SNode __thisNode__) {
    return __thisNode__;
  }
  /*package*/ static String treeViewLabel_id7Atos1ybm9U(@NotNull SNode __thisNode__) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(__thisNode__, LINKS.sourceInstance$mM0T), LINKS.ref$H$FL), PROPS.name$MnvL) + "." + SPropertyOperations.getString(SLinkOperations.getTarget(__thisNode__, LINKS.sourcePort$mT3n), PROPS.name$MnvL) + " -> " + AbstractBusType__BehaviorDescriptor.getName_id4lFnCmbF7lD.invoke(WireTarget__BehaviorDescriptor.connectedBusType_id4lFnCmbEK5U.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.wireTarget$WCE5)));
  }
  /*package*/ static SNode getGoverningPort_idmIQkxg5V$2(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(__thisNode__, LINKS.sourcePort$mT3n);
  }
  /*package*/ static SNode getTarget_id3E8pWteyf_5(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(__thisNode__, LINKS.wireTarget$WCE5), LINKS.target$Ll8l);
  }

  /*package*/ WireConnector__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((AbstractTreeViewNode) getTreeNode_id7NyyyjNtbn2(node, (String) parameters[0]));
      case 1:
        return (T) ((SNode) kind_id6LfBX8Yl7Hz(node));
      case 2:
        return (T) ((SNode) getTypedContextNode_id4fgA7QrKR89(node));
      case 3:
        return (T) ((String) treeViewLabel_id7Atos1ybm9U(node));
      case 4:
        return (T) ((SNode) getGoverningPort_idmIQkxg5V$2(node));
      case 5:
        return (T) ((SNode) getTarget_id3E8pWteyf_5(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
  private static SNode createHardwareKind_opimz8_a0a1() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.HardwareKind$ev);
    return n0.getResult();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink wireTarget$WCE5 = MetaAdapterFactory.getContainmentLink(0xc35abfa80db04d42L, 0xbb3ff46112aeb888L, 0x2fd25306d6b99d15L, 0x443d0f2f0f405a2dL, "wireTarget");
    /*package*/ static final SContainmentLink sourceInstance$mM0T = MetaAdapterFactory.getContainmentLink(0xc35abfa80db04d42L, 0xbb3ff46112aeb888L, 0x2fd25306d6b99d15L, 0x2fd25306d6b99df7L, "sourceInstance");
    /*package*/ static final SReferenceLink ref$H$FL = MetaAdapterFactory.getReferenceLink(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x7fdf70a1447d7f29L, 0x7fdf70a1447d7f36L, "ref");
    /*package*/ static final SReferenceLink sourcePort$mT3n = MetaAdapterFactory.getReferenceLink(0xc35abfa80db04d42L, 0xbb3ff46112aeb888L, 0x2fd25306d6b99d15L, 0x2fd25306d6b99e00L, "sourcePort");
    /*package*/ static final SReferenceLink target$Ll8l = MetaAdapterFactory.getReferenceLink(0xc35abfa80db04d42L, 0xbb3ff46112aeb888L, 0x443d0f2f0f397aadL, 0x443d0f2f0f445fbeL, "target");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept HardwareKind$ev = MetaAdapterFactory.getConcept(0xc35abfa80db04d42L, 0xbb3ff46112aeb888L, 0x952418520a360f2L, "org.iets3.components.hardware.structure.HardwareKind");
  }
}
