package org.iets3.analysis.base.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconLoadingUtil;

public class IconContainer {
  protected static Icon ICON0 = IconLoadingUtil.loadIcon("/icons/running-stick-figure.svg", IconContainer.class);
  protected static Icon ICON1 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_7.png" : "TextIcon_7.png"), IconContainer.class);
  protected static Icon ICON2 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_4.png" : "TextIcon_4.png"), IconContainer.class);
  protected static Icon ICON3 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_1.png" : "TextIcon_1.png"), IconContainer.class);
  protected static Icon ICON4 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_2.png" : "TextIcon_2.png"), IconContainer.class);
  protected static Icon ICON5 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_5.png" : "TextIcon_5.png"), IconContainer.class);
  protected static Icon ICON6 = IconLoadingUtil.loadIcon((IconLoadingUtil.isNewUIActive() ? "TextIconNewUI_3.png" : "TextIcon_3.png"), IconContainer.class);
}
