package org.iets3.analysis.base.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import java.util.Arrays;

public enum ISolvableTaskStatus {
  Timeout(IconContainer.ICON1, 6),
  Failure(IconContainer.ICON2, 5),
  Running(IconContainer.ICON3, 2),
  Done(IconContainer.ICON4, 4),
  Rejected(IconContainer.ICON5, 4),
  Queued(IconContainer.ICON6, 3);


  private Icon icon;
  private int sortingPriority;

  private ISolvableTaskStatus(Icon icon, int prio) {
    this.icon = icon;
    this.sortingPriority = prio;
  }
  public Icon icon() {
    return icon;
  }

  public int sortingPriority() {
    return this.sortingPriority;
  }

  public boolean isStopped() {
    return Arrays.asList(ISolvableTaskStatus.Rejected, ISolvableTaskStatus.Timeout, ISolvableTaskStatus.Failure, ISolvableTaskStatus.Done).contains(this);
  }
}
