package org.iets3.core.expr.base.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.Extension;
import jetbrains.mps.logging.Logger;

public class DefaultIdentifierConfiguratorExtension extends Extension.Default<IdentifierConfigurator> {
  private static final Logger LOG = Logger.getLogger(DefaultIdentifierConfiguratorExtension.class);
  public DefaultIdentifierConfiguratorExtension() {
    super("org.iets3.core.expr.base.identifierConfigurator");
  }

  public void activate() {
    if (LOG.isInfoLevel()) {
      LOG.info("ExtensionPoint implementation DefaultIdentifierConfiguratorExtension is activated");
    }
  }
  public void deactivate() {
    if (LOG.isInfoLevel()) {
      LOG.info("ExtensionPoint implementation DefaultIdentifierConfiguratorExtension is deactivated");
    }
  }

  public IdentifierConfigurator get() {
    return new DefaultIdentifierConfigurator();
  }
}
