package org.iets3.core.expr.tests.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.iets3.core.expr.tests.behavior.TestSubjectAdapter__BehaviorDescriptor;
import org.iets3.core.expr.tests.behavior.AbstractVectorCollection__BehaviorDescriptor;
import org.iets3.core.expr.tests.behavior.TestDataProducer__BehaviorDescriptor;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class check_VectorProducer_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_VectorProducer_NonTypesystemRule() {
  }
  public void applyRule(final SNode vp, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    for (SNode arg : ListSequence.fromList(TestSubjectAdapter__BehaviorDescriptor.arguments_id1bwJEEeSLhl.invoke(AbstractVectorCollection__BehaviorDescriptor.subject_id1bwJEEeTss8.invoke(TestDataProducer__BehaviorDescriptor.coll_id1bwJEEfGuY4.invoke(vp))))) {
      SNode tt = TypecheckingFacade.getFromContext().getTypeOf(arg);
      if (!((boolean) TestDataProducer__BehaviorDescriptor.supportsType_id1bwJEEfKt$D.invoke(vp, tt))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(vp, "type not supported: " + BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(tt), "r:8b1d85a0-933d-4f71-99e8-5435698868f9(org.iets3.core.expr.tests.typesystem)", "1360296727231491981", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.TestDataProducer$U6;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TestDataProducer$U6 = MetaAdapterFactory.getConcept(0xd441fba0f46b43cdL, 0xb723dad7b65da615L, 0x12e0beaa8fa80027L, "org.iets3.core.expr.tests.structure.TestDataProducer");
  }
}
