package test.org.iets3.analysis.base.highlighter;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import java.util.concurrent.CompletableFuture;
import java.util.List;
import org.iets3.core.base.behavior.IResult;
import org.iets3.analysis.base.behavior.ISolvable__BehaviorDescriptor;
import jetbrains.mps.nodeEditor.Highlighter;
import java.util.concurrent.TimeUnit;
import org.junit.Assert;
import jetbrains.mps.nodeEditor.checking.UpdateResult;
import org.iets3.analysis.base.plugin.SolverChecker;
import java.util.Collection;
import jetbrains.mps.nodeEditor.EditorMessage;
import jetbrains.mps.errors.MessageStatus;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

@MPSLaunch
public class TestSolverChecker_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(TestSolverChecker_Test.class).projectPath(null).modelRef("r:548037fc-8928-4e47-be57-455956a745c9(test.org.iets3.analysis.base.highlighter@tests)").reopenProject(false).build());

  public TestSolverChecker_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_TestSolverChecker() throws Throwable {
    new TestBody(this).testMethod();
  }

  /*package*/ static class TestBody extends BaseEditorTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("8923074921376738039", "");
      CompletableFuture<List<IResult>> runManuallyAsync = ISolvable__BehaviorDescriptor.runManuallyAsync_id7QODtLvTFnz.invoke(getAnnotatedNode("sut"));
      Highlighter highlighter = null;
      try {
        List<IResult> iresults = runManuallyAsync.get(5, TimeUnit.SECONDS);
        Assert.assertEquals(1, iresults.size());
        IResult iresult = iresults.get(0);
        String errMsg = (String) iresult.getErrorMessage();

        UpdateResult.Completed updateResult = (UpdateResult.Completed) new SolverChecker().update(getEditorComponent(), true, true, null);
        Collection<EditorMessage> myMessages = updateResult.myMessages;

        Assert.assertEquals(1, myMessages.size());
        EditorMessage message = myMessages.iterator().next();
        Assert.assertEquals(message.getFormattedMessage(), errMsg);
        IResult.MessageType messageType = iresult.messageType();
        Assert.assertEquals(IResult.MessageType.Error, messageType);
        MessageStatus status = message.getStatus();
        Assert.assertEquals(MessageStatus.ERROR, status);

        Assert.assertTrue(Sequence.fromIterable(iresult.targetNodes()).contains(message.getNode()));
        Assert.assertEquals(1, Sequence.fromIterable(iresult.targetNodes()).count());
      } catch (ExecutionException e) {
        throw new RuntimeException(e);
      } catch (TimeoutException e) {
        throw new RuntimeException(e);
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      } finally {
      }


    }
  }
}
