package org.iets3.core.expr.genjava.util.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_KFMaybeNot;
  private ConceptPresentation props_KFMultiAnd;
  private ConceptPresentation props_KFMultiConditional;
  private ConceptPresentation props_KFMultiOr;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.KFMaybeNot:
        if (props_KFMaybeNot == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder(0x15d858db2d214ae9L, 0x90c4f595086d0bdfL, 0x2acea3560c2eebb6L);
          cpb.deprecateAggregation(0x2acea3560c2eeed9L, "expr_old");
          cpb.rawPresentation("maybenot");
          props_KFMaybeNot = cpb.create();
        }
        return props_KFMaybeNot;
      case LanguageConceptSwitch.KFMultiAnd:
        if (props_KFMultiAnd == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("and");
          cpb.rawPresentation("and");
          props_KFMultiAnd = cpb.create();
        }
        return props_KFMultiAnd;
      case LanguageConceptSwitch.KFMultiConditional:
        if (props_KFMultiConditional == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("abstract expression for KF multi conditionals");
          props_KFMultiConditional = cpb.create();
        }
        return props_KFMultiConditional;
      case LanguageConceptSwitch.KFMultiOr:
        if (props_KFMultiOr == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("or");
          cpb.rawPresentation("or");
          props_KFMultiOr = cpb.create();
        }
        return props_KFMultiOr;
    }
    return null;
  }
}
