package org.iets3.safety.attributes.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class GrammarCellsSubstituteMenu_ControllabilityValue extends SubstituteMenuBase {
  public GrammarCellsSubstituteMenu_ControllabilityValue() {
    super(true, new EditorMenuDescriptorBase("contribution to the " + "default substitute menu for " + "ControllabilityValue", null));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new GrammarCellsSubstituteMenuPart_qiluqh_a());
    return result;
  }

  private class GrammarCellsSubstituteMenuPart_qiluqh_a extends GrammarCellsSubstituteMenuPart {
    @Override
    public SModule getModule(SRepository repository) {
      return PersistenceFacade.getInstance().createModuleReference("3d5cb920-2b5f-4dcb-8349-68b4bf077e63(org.iets3.safety.attributes)").resolve(repository);
    }
    @Override
    public SAbstractConcept getExpectedOutputConcept() {
      return CONCEPTS.ControllabilityValue$80;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ControllabilityValue$80 = MetaAdapterFactory.getConcept(0x3d5cb9202b5f4dcbL, 0x834968b4bf077e63L, 0x710b4f5487c7a15dL, "org.iets3.safety.attributes.structure.ControllabilityValue");
  }
}
