package org.iets3.core.junit.interpreter.run.configuration.plugin;

/*Generated by MPS */

import javax.swing.JComponent;
import com.intellij.ui.components.JBPanel;
import javax.swing.BoxLayout;
import javax.swing.Box;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.project.Project;
import jetbrains.mps.baseLanguage.unitTest.execution.settings.InProcessJBCheckBox;

/**
 * extends JComponent only of idiotic logic in the editor part of run configurations, where you must pass JComponent with no context
 */
public final class JUnitInterpreterConfigurationEditorComponent extends JComponent {
  private final JBPanel myPanel = new JBPanel();
  private final JUnitInterpreterScopeAndPanels myScopeAndPanels;

  private JBPanel createSaveCachesPanel() {
    JBPanel saveCachesPanel = new JBPanel();
    saveCachesPanel.setLayout(new BoxLayout(saveCachesPanel, BoxLayout.X_AXIS));
    saveCachesPanel.add(Box.createHorizontalGlue());
    return saveCachesPanel;
  }

  public JUnitInterpreterConfigurationEditorComponent(@NotNull Project project) {
    myPanel.setLayout(new BoxLayout(myPanel, BoxLayout.Y_AXIS));
    myScopeAndPanels = new JUnitInterpreterScopeAndPanels(project);
    myPanel.add(myScopeAndPanels.getPanel());

    myPanel.add(createSaveCachesPanel());
    init();
  }


  private void init() {
    for (final InProcessJBCheckBox checkbox : myScopeAndPanels.getInProcessCheckBoxes()) {
      checkbox.forceUpdate();
    }
  }

  /**
   * Disable supplied component when 'in-process' setting has been activated.
   * Intended for use from run configurations that use JUnit settings along with other settings that may need to reflect 
   * state of the 'in-process' setting.
   */
  public void disableComponentWhenInProcess(JComponent... component) {
    for (final InProcessJBCheckBox checkbox : myScopeAndPanels.getInProcessCheckBoxes()) {
      for (JComponent c : component) {
        checkbox.registerDisableIffSelectedUpdater(c);
      }
      checkbox.forceUpdate();
    }
  }


  public void apply(JUnitInterpreterSettings_Configuration configuration) {
    myScopeAndPanels.apply(configuration);
  }

  public void reset(JUnitInterpreterSettings_Configuration settings) {
    myScopeAndPanels.reset(settings);
  }


  public JBPanel getPanel() {
    return myPanel;
  }

  public void dispose() {
    myScopeAndPanels.dispose();
  }
}
