package org.iets3.core.trace.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import org.iets3.core.trace.behavior.TraceKind__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class ITraceTargetProvider_Constraints extends BaseConstraintsDescriptor {
  /*package*/ ITraceTargetProvider_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.ITraceTargetProvider$zD, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.traceTarget$Q_qM, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:ddcd6ddf-0912-41ff-95f9-427940f981c1(org.iets3.core.trace.constraints)", "596856272726854620");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forResolvableElements(TraceKind__BehaviorDescriptor.traceableElements_idx8tpS_QfyE.invoke(SLinkOperations.getTarget(SNodeOperations.cast((((_context.getReferenceNode() == null) ? _context.getContextNode() : SNodeOperations.getParent(_context.getReferenceNode()))), CONCEPTS.ITrace$ef), LINKS.traceKind$_UHM)));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept ITraceTargetProvider$zD = MetaAdapterFactory.getInterfaceConcept(0x7d21cc4b4c2441dbL, 0x98688af4a7f3eba9L, 0x1d637a1db4e71b4cL, "org.iets3.core.trace.structure.ITraceTargetProvider");
    /*package*/ static final SInterfaceConcept ITrace$ef = MetaAdapterFactory.getInterfaceConcept(0x7d21cc4b4c2441dbL, 0x98688af4a7f3eba9L, 0x1d637a1db4e6503fL, "org.iets3.core.trace.structure.ITrace");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink traceTarget$Q_qM = MetaAdapterFactory.getReferenceLink(0x7d21cc4b4c2441dbL, 0x98688af4a7f3eba9L, 0x1d637a1db4e71b4cL, 0x1d637a1db4e71b4dL, "traceTarget");
    /*package*/ static final SContainmentLink traceKind$_UHM = MetaAdapterFactory.getContainmentLink(0x7d21cc4b4c2441dbL, 0x98688af4a7f3eba9L, 0x1d637a1db4e6503fL, 0x1d637a1db4e65040L, "traceKind");
  }
}
