package org.iets3.core.expr.typetags.physunits.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.iets3.core.expr.typetags.physunits.behavior.ConversionSpecifier__BehaviorDescriptor;
import java.util.Map;
import org.iets3.core.expr.typetags.physunits.behavior.NamedKeyWrapper;
import org.iets3.core.expr.base.runtime.runtime.Fraction;
import org.iets3.core.expr.typetags.physunits.behavior.UnitConversionUtil;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.iets3.core.expr.typetags.physunits.behavior.Exponent__BehaviorDescriptor;
import org.iets3.core.expr.typetags.physunits.behavior.ExpressionChecker;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Objects;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_ConversionSpecifier_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_ConversionSpecifier_NonTypesystemRule() {
  }
  public void applyRule(final SNode specifier, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p) != null) {
      SNode type = TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p));

      if (SPropertyOperations.getBoolean(ConversionSpecifier__BehaviorDescriptor.getConversionRule_id1wGuEUvYk55.invoke(specifier), PROPS.isEager$qBr0)) {
        Map<NamedKeyWrapper, Fraction> expTypeSpec = UnitConversionUtil.getMap_Type(type);
        Map<NamedKeyWrapper, Fraction> toTypeSpec = UnitConversionUtil.getMap_IUnit(SLinkOperations.getTarget(SLinkOperations.getTarget(ConversionSpecifier__BehaviorDescriptor.getConversionRule_id1wGuEUvYk55.invoke(specifier), LINKS.targetUnit$cNlh), LINKS.unit$nTeG), 1);

        if (!((boolean) UnitConversionUtil.matchingMappings(expTypeSpec, toTypeSpec)._0())) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p), "the conversion expression's unit and the rule's target unit do not match", "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "2315408579356842760", null, errorTarget);
          }
        }
      } else {
        SNode specification = SNodeOperations.as(UnitConversionUtil.getSpecification(type), CONCEPTS.UnitSpecification$6j);

        boolean cond1 = specification != null && Sequence.fromIterable(SNodeOperations.ofConcept(UnitConversionUtil.extractUnitsFromMultiplication(SLinkOperations.getTarget(specification, LINKS.specification$d6YI)), CONCEPTS.UnitExponent$BW)).all((it) -> SLinkOperations.getTarget(it, LINKS.exponent$z83d) != null && (int) Exponent__BehaviorDescriptor.getNumerator_id3j3yk3guAC3.invoke(SLinkOperations.getTarget(it, LINKS.exponent$z83d)) == 0);
        boolean cond2 = specification == null && SNodeOperations.isInstanceOf(type, CONCEPTS.Type$WK);

        if (!(cond1 || cond2)) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p), "a lazy conversion expression must not have a type with unit", "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "2315408579356860850", null, errorTarget);
          }
        }
      }

      if (ExpressionChecker.hasDivExpressionBeforeMulExpression(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportWarning(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p), "possible loss of precision (division before multiplication)", "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "5676846279064892361", null, errorTarget);
        }
      }

      // check for inner conversion expressions whose conversion specifier is more restrictive
      // than the type of this conversion specifier
      for (SNode convertExpression : ListSequence.fromList(SNodeOperations.getNodeDescendants(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p), CONCEPTS.ConvertExpression$Xc, true, new SAbstractConcept[]{}))) {
        if (SLinkOperations.getTarget(convertExpression, LINKS.conversionSpecifier$hrvU) != null) {
          SNode outerType = SLinkOperations.getTarget(specifier, LINKS.type$poAd);
          SNode innerType = SLinkOperations.getTarget(SLinkOperations.getTarget(convertExpression, LINKS.conversionSpecifier$hrvU), LINKS.type$poAd);
          // this specifier has universal type, but the nested type is not universal
          boolean c1 = innerType != null && outerType == null;
          // the inner type is a subtype of the type of this specifier
          // the trick with the concepts is needed because the isStrongSubtype returns true when invoked
          // with the exact same types
          boolean c2 = innerType != null && outerType != null && !(Objects.equals(SNodeOperations.getConcept(innerType), SNodeOperations.getConcept(outerType))) && TypecheckingFacade.getFromContext().isStrongSubtype(innerType, outerType);
          if (c1 || c2) {
            {
              final MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(convertExpression, "a more restrictive type is used in the conversion specifier", "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "5435475783431038611", null, errorTarget);
            }
          }
        }
      }

      if (ExpressionChecker.isSelfReferencingSpecifier(specifier)) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(specifier, "self-referencing convert expression", "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "3156023081160644881", null, errorTarget);
        }
      }

      if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p), CONCEPTS.ValExpression$hl)) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(specifier, LINKS.expression$BZ0p), "a conversion formula is not allowed to consist of only a val expression", "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "4240468146476564043", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.ConversionSpecifier$X$;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expression$BZ0p = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x182c7aae9fea4574L, 0x182c7aae9fee3f05L, "expression");
    /*package*/ static final SContainmentLink targetUnit$cNlh = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0xed6abcb370b28cbL, 0x6a9f53f6f54cb11bL, "targetUnit");
    /*package*/ static final SReferenceLink unit$nTeG = MetaAdapterFactory.getReferenceLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d4dc5L, 0x73b48a125b0daafcL, "unit");
    /*package*/ static final SContainmentLink specification$d6YI = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d411dL, 0x73b48a125b0dab03L, "specification");
    /*package*/ static final SContainmentLink exponent$z83d = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x74818abc54714f3eL, 0x74818abc54715a85L, "exponent");
    /*package*/ static final SContainmentLink type$poAd = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x182c7aae9fea4574L, 0x182c7aaea0320b8dL, "type");
    /*package*/ static final SReferenceLink conversionSpecifier$hrvU = MetaAdapterFactory.getReferenceLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x3930d8ab4c0e6285L, 0x8ac4b7baaeabc73L, "conversionSpecifier");
  }

  private static final class PROPS {
    /*package*/ static final SProperty isEager$qBr0 = MetaAdapterFactory.getProperty(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0xed6abcb370b28cbL, 0x182c7aae9ff63560L, "isEager");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept UnitSpecification$6j = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d411dL, "org.iets3.core.expr.typetags.physunits.structure.UnitSpecification");
    /*package*/ static final SConcept UnitExponent$BW = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x74818abc54714f3eL, "org.iets3.core.expr.typetags.physunits.structure.UnitExponent");
    /*package*/ static final SConcept Type$WK = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x670d5e92f854a614L, "org.iets3.core.expr.base.structure.Type");
    /*package*/ static final SConcept ConvertExpression$Xc = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x3930d8ab4c0e6285L, "org.iets3.core.expr.typetags.physunits.structure.ConvertExpression");
    /*package*/ static final SConcept ValExpression$hl = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x47f53137d1e3b2aeL, "org.iets3.core.expr.typetags.physunits.structure.ValExpression");
    /*package*/ static final SConcept ConversionSpecifier$X$ = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x182c7aae9fea4574L, "org.iets3.core.expr.typetags.physunits.structure.ConversionSpecifier");
  }
}
