package org.iets3.core.expr.typetags.physunits.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_UnitMul_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_UnitMul_InferenceRule() {
  }
  public void applyRule(final SNode unitMul, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final SNode lefT = typeCheckingContext.typeOf(SLinkOperations.getTarget(unitMul, LINKS.left$sr9k), "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504432", true);
      typeCheckingContext.whenConcrete(lefT, () -> {
        {
          final SNode rightT = typeCheckingContext.typeOf(SLinkOperations.getTarget(unitMul, LINKS.right$2nEP), "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504426", true);
          typeCheckingContext.whenConcrete(rightT, () -> {
            if (!(typeCheckingContext.isSingleTypeComputation())) {
              {
                SNode _nodeToCheck_1029348928467 = unitMul;
                EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504396", 0, null);
                typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.getExpandedNode(lefT), (SNode) createQuantityType_ksfd6c_a1a0c0a0a0b0a1a0a1a0b0a0b(), true, true, _info_12389875345);
              }
            }
            if (!(typeCheckingContext.isSingleTypeComputation())) {
              {
                SNode _nodeToCheck_1029348928467 = unitMul;
                EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504402", 0, null);
                typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.getExpandedNode(rightT), (SNode) createQuantityType_ksfd6c_a1a0c0a0b0b0a1a0a1a0b0a0b(), true, true, _info_12389875345);
              }
            }
            SNode node = createQuantityMultiplicationType_ksfd6c_a0c0b0a1a0a1a0b0a0b((SNode) typeCheckingContext.getExpandedNode(lefT), ((SNode) typeCheckingContext.getExpandedNode(rightT)));
            node = GroupHelper.minimize(node);
            {
              SNode _nodeToCheck_1029348928467 = unitMul;
              EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504408", 0, null);
              typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504424", true), (SNode) node, _info_12389875345);
            }
          }, "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504394", false, false);
        }
      }, "r:d4f1532d-fc5c-419f-84ee-daef42867c8e(org.iets3.core.expr.typetags.physunits.typesystem)", "8395143721870504392", false, false);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.UnitMultiplication$sx;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static SNode createQuantityType_ksfd6c_a1a0c0a0a0b0a1a0a1a0b0a0b() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.QuantityType$2O);
    return n0.getResult();
  }
  private static SNode createQuantityType_ksfd6c_a1a0c0a0b0b0a1a0a1a0b0a0b() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.QuantityType$2O);
    return n0.getResult();
  }
  private static SNode createQuantityMultiplicationType_ksfd6c_a0c0b0a1a0a1a0b0a0b(SNode p0, SNode p1) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.QuantityMultiplicationType$HU);
    n0.forChild(LINKS.left$4zfX).initNode(p0, CONCEPTS.QuantityType$2O, true);
    n0.forChild(LINKS.right$ps6W).initNode(p1, CONCEPTS.QuantityType$2O, true);
    return n0.getResult();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink left$sr9k = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x74818abc5471020dL, 0x74818abc54710afeL, "left");
    /*package*/ static final SContainmentLink right$2nEP = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x74818abc5471020dL, 0x74818abc54710e0cL, "right");
    /*package*/ static final SContainmentLink left$4zfX = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x414a129fbf6f1373L, 0x1be25d17bc5c502bL, "left");
    /*package*/ static final SContainmentLink right$ps6W = MetaAdapterFactory.getContainmentLink(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x414a129fbf6f1373L, 0x1be25d17bc5c529dL, "right");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept UnitMultiplication$sx = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x74818abc5471020dL, "org.iets3.core.expr.typetags.physunits.structure.UnitMultiplication");
    /*package*/ static final SConcept QuantityType$2O = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x625831af8c1989b9L, "org.iets3.core.expr.typetags.physunits.structure.QuantityType");
    /*package*/ static final SConcept QuantityMultiplicationType$HU = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x414a129fbf6f1373L, "org.iets3.core.expr.typetags.physunits.structure.QuantityMultiplicationType");
  }
}
