package org.iets3.core.expr.dataflow.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class GrammarCellsSubstituteMenu_OutsideEndpoint extends SubstituteMenuBase {
  public GrammarCellsSubstituteMenu_OutsideEndpoint() {
    super(true, new EditorMenuDescriptorBase("default substitute menu for OutsideEndpoint. Generated from implicit smart reference attribute.", new SNodePointer("r:a9ed28db-11a2-453b-b8cd-4dbf2ae73280(org.iets3.core.expr.dataflow.structure)", "4131570352307197505")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new GrammarCellsSubstituteMenuPart_qphpzz_a());
    return result;
  }

  private class GrammarCellsSubstituteMenuPart_qphpzz_a extends GrammarCellsSubstituteMenuPart {
    @Override
    public SModule getModule(SRepository repository) {
      return PersistenceFacade.getInstance().createModuleReference("cee4aa62-aca9-4f26-9602-75129cd457c9(org.iets3.core.expr.dataflow)").resolve(repository);
    }
    @Override
    public SAbstractConcept getExpectedOutputConcept() {
      return CONCEPTS.OutsideEndpoint$pO;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept OutsideEndpoint$pO = MetaAdapterFactory.getConcept(0xcee4aa62aca94f26L, 0x960275129cd457c9L, 0x395649586dce5641L, "org.iets3.core.expr.dataflow.structure.OutsideEndpoint");
  }
}
