package test.org.iets3.variability.configuration.base.inheritance;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.junit.Assert;
import org.iets3.variability.configuration.base.behavior.AbstractFeatureConfiguration__BehaviorDescriptor;

@MPSLaunch
public class FindConfigurationThroughFeatureModelInclude_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(FindConfigurationThroughFeatureModelInclude_Test.class).projectPath(null).modelRef("r:67b8c8a1-c2c2-4db8-bb17-956b347d6975(test.org.iets3.variability.configuration.base.inheritance@tests)").reopenProject(null).build());

  public FindConfigurationThroughFeatureModelInclude_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_findConfigOfFeatureInIncludedFeatureModel() throws Throwable {
    new TestBody(this).test_findConfigOfFeatureInIncludedFeatureModel();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    protected void initTestNodes() {
      prepareTestNodes("6221111985299954286");
    }

    public void test_findConfigOfFeatureInIncludedFeatureModel() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        // Path from Car to Red is [body, Body, Red], but the configuration has no node for the included root 'Body'
        Assert.assertSame(getAnnotatedNode("redCfg"), AbstractFeatureConfiguration__BehaviorDescriptor.findConfiguration_id4zfp5i3BhvO.invoke(getAnnotatedNode("car"), getAnnotatedNode("red")));
      });
    }

  }
}
