package org.iets3.core.expr.base.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.editor.runtime.cells.BigCellUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import jetbrains.mps.internal.collections.runtime.IterableUtils;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.iets3.core.expr.base.behavior.SimpleValueInspector__BehaviorDescriptor;
import org.iets3.core.expr.base.plugin.MultiLineEditorCell;
import com.intellij.ui.JBColor;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import java.awt.Color;
import jetbrains.mps.nodeEditor.MPSColors;
import de.itemis.mps.editor.celllayout.runtime.cells.HorizontalLineCell;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.openapi.editor.update.AttributeKind;
import org.iets3.core.expr.base.runtime.runtime.ICustomStringForValueInspector;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

/*package*/ class SimpleValueInspector_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public SimpleValueInspector_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createAlternation_0();
  }

  private EditorCell createAlternation_0() {
    boolean alternationCondition = true;
    alternationCondition = nodeCondition_dvvx3u_a0();
    EditorCell editorCell = null;
    if (alternationCondition) {
      editorCell = createCollection_0();
    } else {
      editorCell = createCollection_2();
    }
    EditorCell bigCell = BigCellUtil.findBigCell(editorCell, getNode());
    if (bigCell != null) {
      bigCell.setBig(true);
      setCellContext(bigCell);
    }
    return editorCell;
  }
  private boolean nodeCondition_dvvx3u_a0() {
    return SPropertyOperations.getBoolean(myNode, PROPS.showOnTop$2g$e);
  }
  private EditorCell createCollection_0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_dvvx3u_a0");
    editorCell.addEditorCell(createCollection_1());
    editorCell.addEditorCell(createHorizontalLineCell_1());
    editorCell.addEditorCell(createAttributedNodeCell_0());
    return editorCell;
  }
  private EditorCell createCollection_1() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_dvvx3u_a0a");
    deleteValueInspector.setCellActions(editorCell, myNode, getEditorContext());
    editorCell.addEditorCell(createCustom_0());
    return editorCell;
  }
  private EditorCell createCustom_0() {
    AbstractCellProvider provider = ((_FunctionTypes._return_P0_E0<AbstractCellProvider>) () -> {
      String s = IterableUtils.join(ListSequence.fromList(SimpleValueInspector__BehaviorDescriptor.getValues_id2ufoZQIKMt6.invoke(myNode)).select((it) -> it.toString()), "\n");
      return new MultiLineEditorCell(myNode, s, JBColor.foreground(), null).createCellProvider(getEditorContext(), myNode);
    }).invoke();
    EditorCell editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("Custom_dvvx3u_a0a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.DRAW_BORDER, true);
    style.set(StyleAttributes.getInstance().<Color>getAttribute("de.itemis.mps.editor.celllayout.styles", "_border-color"), getStyleRegistry().getSimpleColor(MPSColors.blue));
    style.set(StyleAttributes.getInstance().<Integer>getAttribute("de.itemis.mps.editor.celllayout.styles", "_border-size"), 2);
    style.set(StyleAttributes.BACKGROUND_COLOR, getStyleRegistry().getSimpleColor(new Color(11989498)));
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createHorizontalLineCell_0(EditorContext editorContext, SNode node) {
    HorizontalLineCell editorCell = new HorizontalLineCell(editorContext, node);
    editorCell.setCellId("HorizontalLineCell_dvvx3u_b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.getInstance().<Integer>getAttribute("de.itemis.mps.editor.celllayout.styles", "_horizontal-line-width"), 2);
    style.set(StyleAttributes.getInstance().<Color>getAttribute("de.itemis.mps.editor.celllayout.styles", "_horizontal-line-color"), getStyleRegistry().getSimpleColor(MPSColors.gray));
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createHorizontalLineCell_1() {
    return createHorizontalLineCell_0(getEditorContext(), myNode);
  }
  private EditorCell createAttributedNodeCell_0() {
    EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
    EditorCell editorCell = getUpdateSession().getAttributedCell(AttributeKind.NODE, myNode);
    Style style = new StyleImpl();
    style.set(StyleAttributes.BASE_LINE_CELL, true);
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createCollection_2() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_dvvx3u_a0_0");
    editorCell.addEditorCell(createAttributedNodeCell_1());
    editorCell.addEditorCell(createCollection_3());
    return editorCell;
  }
  private EditorCell createAttributedNodeCell_1() {
    EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
    EditorCell editorCell = getUpdateSession().getAttributedCell(AttributeKind.NODE, myNode);
    return editorCell;
  }
  private EditorCell createCollection_3() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_dvvx3u_b0a");
    deleteValueInspector.setCellActions(editorCell, myNode, getEditorContext());
    editorCell.addEditorCell(createCustom_1());
    return editorCell;
  }
  private EditorCell createCustom_1() {
    AbstractCellProvider provider = ((_FunctionTypes._return_P0_E0<AbstractCellProvider>) () -> {
      String s = IterableUtils.join(ListSequence.fromList(SimpleValueInspector__BehaviorDescriptor.getValues_id2ufoZQIKMt6.invoke(myNode)).select((it) -> {
        if (it instanceof ICustomStringForValueInspector) {
          return ((ICustomStringForValueInspector) it).valueInspectorString();
        }
        return it.toString();
      }), "\n");
      return new MultiLineEditorCell(myNode, s, JBColor.foreground(), null).createCellProvider(getEditorContext(), myNode);
    }).invoke();
    EditorCell editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("Custom_dvvx3u_a1a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.DRAW_BORDER, true);
    style.set(StyleAttributes.getInstance().<Color>getAttribute("de.itemis.mps.editor.celllayout.styles", "_border-color"), getStyleRegistry().getSimpleColor(MPSColors.blue));
    style.set(StyleAttributes.getInstance().<Integer>getAttribute("de.itemis.mps.editor.celllayout.styles", "_border-size"), 2);
    style.set(StyleAttributes.BACKGROUND_COLOR, getStyleRegistry().getSimpleColor(new Color(11989498)));
    editorCell.getStyle().putAll(style);
    return editorCell;
  }

  private static final class PROPS {
    /*package*/ static final SProperty showOnTop$2g$e = MetaAdapterFactory.getProperty(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x278f63fdaec2d699L, 0x6283e1a874774867L, "showOnTop");
  }
}
