package org.iets3.core.expr.process.interpreter.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.interpreter.rt.InterpreterBase;
import java.util.List;
import com.mbeddr.mpsutil.interpreter.rt.IEvaluator;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import com.mbeddr.mpsutil.interpreter.rt.ConceptEvaluatorBase;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.mpsutil.interpreter.rt.IContext;
import com.mbeddr.mpsutil.interpreter.rt.ICoverageAnalyzer;
import com.mbeddr.mpsutil.interpreter.rt.ComputationTrace;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.iets3.core.expr.mutable.plugin.InteractorValue;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import org.iets3.core.expr.mutable.plugin.InterceptorHelper;
import org.iets3.core.expr.process.plugin.TakeTurnsOrderedInterceptorState;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import com.mbeddr.mpsutil.interpreter.rt.DummyComputationTrace;
import com.mbeddr.mpsutil.interpreter.rt.StopAndReturnException;
import com.mbeddr.mpsutil.interpreter.rt.InterpreterEscapeException;
import com.mbeddr.mpsutil.interpreter.rt.InterpreterRuntimeException;
import com.mbeddr.mpsutil.interpreter.rt.EvaluatorInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.Objects;
import org.iets3.core.expr.mutable.behavior.IInteractor__BehaviorDescriptor;
import com.mbeddr.mpsutil.interpreter.rt.ITypeMapper;
import com.mbeddr.mpsutil.interpreter.rt.IRelationship;
import com.mbeddr.mpsutil.interpreter.rt.InterpretBeforeRelationshipImpl;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class InterpreterExprProcessInterpreter extends InterpreterBase {
  public InterpreterExprProcessInterpreter() {
    init();
  }

  @Override
  public String getCategory() {
    return "arithmetic";
  }

  protected void populateEvaluators(List<? extends IEvaluator> evaluators) {
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(CONCEPTS.WhoIsNextExpr$JD, "r:10a0374b-c100-41eb-932b-76142fca171c(org.iets3.core.expr.process.interpreter.plugin)/6076143548507141005", true) {
      public Object evaluateEvaluator(final SNode node, IContext context, ICoverageAnalyzer coverage, final ComputationTrace trace) {
        try {
          coverage.visitedEvaluator(this);
          coverage.visitedConcept(this.concept);
          coverage.visitedConcept(SNodeOperations.getConcept(node));
          InteractorValue iv = (InteractorValue) MapSequence.fromMap(context.getEnvironment()).get(InteractorValue.THIS);
          SNode tti = InterceptorHelper.findInterceptor(node, CONCEPTS.TakeTurnsInterceptor$2m);
          if (tti == null) {
            return null;
          }
          TakeTurnsOrderedInterceptorState state = (TakeTurnsOrderedInterceptorState) iv.getSubstate(tti, context, ((_FunctionTypes._return_P0_E0<ComputationTrace>) () -> {
            if (trace != null) {
              return trace;
            } else {
              return new DummyComputationTrace(node);
            }
          }).invoke());
          if (state == null) {
            return null;
          }
          return state.nextParty()._0();
        } catch (StopAndReturnException stop) {
          return stop.value();
        } catch (InterpreterEscapeException ex) {
          throw ex;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("whoIsNext()", node, ex, trace);
        }
      }
      public EvaluatorInfo getInfo() {
        return new EvaluatorInfo("WhoIsNextExpr", "http://127.0.0.1:63320/node?ref=009140a6-c05d-4909-b5a9-7c5ca2f16a0f%2Fi%3A10000001%28org.iets3.core.expr.process.interpreter%40transient113%2Forg.iets3.core.expr.process.interpreter.plugin%400%29%2F6076143548507141005");
      }

      @Override
      public String toString() {
        return "WhoIsNextExpr";
      }

      @Override
      public boolean canLookupBeCached() {
        return true;
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(CONCEPTS.PartyLiteral$2w, "r:10a0374b-c100-41eb-932b-76142fca171c(org.iets3.core.expr.process.interpreter.plugin)/1136100386042332336", true) {
      public Object evaluateEvaluator(SNode node, IContext context, ICoverageAnalyzer coverage, ComputationTrace trace) {
        try {
          coverage.visitedEvaluator(this);
          coverage.visitedConcept(this.concept);
          coverage.visitedConcept(SNodeOperations.getConcept(node));
          return "@[" + SPropertyOperations.getString(node, PROPS.id$Sl6d) + "]";
        } catch (StopAndReturnException stop) {
          return stop.value();
        } catch (InterpreterEscapeException ex) {
          throw ex;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("@()", node, ex, trace);
        }
      }
      public EvaluatorInfo getInfo() {
        return new EvaluatorInfo("PartyLiteral", "http://127.0.0.1:63320/node?ref=009140a6-c05d-4909-b5a9-7c5ca2f16a0f%2Fi%3A10000001%28org.iets3.core.expr.process.interpreter%40transient113%2Forg.iets3.core.expr.process.interpreter.plugin%400%29%2F1136100386042332336");
      }

      @Override
      public String toString() {
        return "PartyLiteral";
      }

      @Override
      public boolean canLookupBeCached() {
        return true;
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(CONCEPTS.EqualsExpression$k4, "r:10a0374b-c100-41eb-932b-76142fca171c(org.iets3.core.expr.process.interpreter.plugin)/4378712714625381740", true) {
      public Object evaluateEvaluator(SNode node, IContext context, ICoverageAnalyzer coverage, ComputationTrace trace) {
        try {
          coverage.visitedEvaluator(this);
          coverage.visitedConcept(this.concept);
          coverage.visitedConcept(SNodeOperations.getConcept(node));
          if (SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(node, LINKS.left$zxUa)), CONCEPTS.PartyType$21) && SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(node, LINKS.right$zBjx)), CONCEPTS.PartyType$21)) {
            return Objects.equals(((Object) castUp(context.getRootInterpreter().evaluate(SLinkOperations.getTarget(node, LINKS.left$zxUa), context, coverage, trace, false), Object.class)), ((Object) castUp(context.getRootInterpreter().evaluate(SLinkOperations.getTarget(node, LINKS.right$zBjx), context, coverage, trace, false), Object.class)));
          }
          return InterpreterBase.__NEXT__INTERPRETER__;
        } catch (StopAndReturnException stop) {
          return stop.value();
        } catch (InterpreterEscapeException ex) {
          throw ex;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("==()", node, ex, trace);
        }
      }
      public EvaluatorInfo getInfo() {
        return new EvaluatorInfo("EqualsExpression", "http://127.0.0.1:63320/node?ref=009140a6-c05d-4909-b5a9-7c5ca2f16a0f%2Fi%3A10000001%28org.iets3.core.expr.process.interpreter%40transient113%2Forg.iets3.core.expr.process.interpreter.plugin%400%29%2F4378712714625381740");
      }

      @Override
      public String toString() {
        return "EqualsExpression";
      }

      @Override
      public boolean canLookupBeCached() {
        return true;
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(CONCEPTS.NotEqualsExpression$kz, "r:10a0374b-c100-41eb-932b-76142fca171c(org.iets3.core.expr.process.interpreter.plugin)/4378712714625413892", true) {
      public Object evaluateEvaluator(SNode node, IContext context, ICoverageAnalyzer coverage, ComputationTrace trace) {
        try {
          coverage.visitedEvaluator(this);
          coverage.visitedConcept(this.concept);
          coverage.visitedConcept(SNodeOperations.getConcept(node));
          if (SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(node, LINKS.left$zxUa)), CONCEPTS.PartyType$21) && SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(node, LINKS.right$zBjx)), CONCEPTS.PartyType$21)) {
            return !(Objects.equals(((Object) castUp(context.getRootInterpreter().evaluate(SLinkOperations.getTarget(node, LINKS.left$zxUa), context, coverage, trace, false), Object.class)), ((Object) castUp(context.getRootInterpreter().evaluate(SLinkOperations.getTarget(node, LINKS.right$zBjx), context, coverage, trace, false), Object.class))));
          }
          return InterpreterBase.__NEXT__INTERPRETER__;
        } catch (StopAndReturnException stop) {
          return stop.value();
        } catch (InterpreterEscapeException ex) {
          throw ex;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("!=()", node, ex, trace);
        }
      }
      public EvaluatorInfo getInfo() {
        return new EvaluatorInfo("NotEqualsExpression", "http://127.0.0.1:63320/node?ref=009140a6-c05d-4909-b5a9-7c5ca2f16a0f%2Fi%3A10000001%28org.iets3.core.expr.process.interpreter%40transient113%2Forg.iets3.core.expr.process.interpreter.plugin%400%29%2F4378712714625413892");
      }

      @Override
      public String toString() {
        return "NotEqualsExpression";
      }

      @Override
      public boolean canLookupBeCached() {
        return true;
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(CONCEPTS.RunProcess$nx, "r:10a0374b-c100-41eb-932b-76142fca171c(org.iets3.core.expr.process.interpreter.plugin)/9163496876328068521", true) {
      public Object evaluateEvaluator(SNode node, IContext context, ICoverageAnalyzer coverage, ComputationTrace trace) {
        try {
          coverage.visitedEvaluator(this);
          coverage.visitedConcept(this.concept);
          coverage.visitedConcept(SNodeOperations.getConcept(node));
          return IInteractor__BehaviorDescriptor.createNewValue_id7WFhXJlVW$d.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(node, LINKS.process$lyo4), LINKS.process$58NI), context);
        } catch (StopAndReturnException stop) {
          return stop.value();
        } catch (InterpreterEscapeException ex) {
          throw ex;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("run()", node, ex, trace);
        }
      }
      public EvaluatorInfo getInfo() {
        return new EvaluatorInfo("RunProcess", "http://127.0.0.1:63320/node?ref=009140a6-c05d-4909-b5a9-7c5ca2f16a0f%2Fi%3A10000001%28org.iets3.core.expr.process.interpreter%40transient113%2Forg.iets3.core.expr.process.interpreter.plugin%400%29%2F9163496876328068521");
      }

      @Override
      public String toString() {
        return "RunProcess";
      }

      @Override
      public boolean canLookupBeCached() {
        return true;
      }
    });
  }


  protected void populateTypeMappers(List<? extends ITypeMapper> typeMappers) {
  }



  protected void populateRelationships(List<? extends IRelationship> relationships) {
    ListSequence.fromList(((List<IRelationship>) relationships)).addElement(new InterpretBeforeRelationshipImpl("org.iets3.core.expr.process.interpreter.plugin.InterpreterExprProcessInterpreter", "org.iets3.core.expr.mutable.interpreter.plugin.InterpreterExprMutateInterpreter"));
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TakeTurnsInterceptor$2m = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x4bbb01110854f1ddL, "org.iets3.core.expr.process.structure.TakeTurnsInterceptor");
    /*package*/ static final SConcept WhoIsNextExpr$JD = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x5452cc5d5469b6dbL, "org.iets3.core.expr.process.structure.WhoIsNextExpr");
    /*package*/ static final SConcept PartyLiteral$2w = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0xfc43d48233b0f23L, "org.iets3.core.expr.process.structure.PartyLiteral");
    /*package*/ static final SConcept PartyType$21 = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0xfc43d48233b0f22L, "org.iets3.core.expr.process.structure.PartyType");
    /*package*/ static final SConcept EqualsExpression$k4 = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86cc6dc9L, "org.iets3.core.expr.base.structure.EqualsExpression");
    /*package*/ static final SConcept NotEqualsExpression$kz = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86cc6dcaL, "org.iets3.core.expr.base.structure.NotEqualsExpression");
    /*package*/ static final SConcept RunProcess$nx = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x7f2b47dbd5d98828L, "org.iets3.core.expr.process.structure.RunProcess");
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$Sl6d = MetaAdapterFactory.getProperty(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0xfc43d48233b0f23L, 0xfc43d48233b3fc7L, "id");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink right$zBjx = MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86c99c15L, 0x46ff3b3d86c99c18L, "right");
    /*package*/ static final SContainmentLink left$zxUa = MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x46ff3b3d86c99c15L, 0x46ff3b3d86c99c16L, "left");
    /*package*/ static final SContainmentLink process$lyo4 = MetaAdapterFactory.getContainmentLink(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x7f2b47dbd5d98828L, 0x56a4de6c51eafaL, "process");
    /*package*/ static final SReferenceLink process$58NI = MetaAdapterFactory.getReferenceLink(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x7f2b47dbd5d9886fL, 0x7f2b47dbd5d98870L, "process");
  }
}
