package org.iets3.core.base.editor;

/*Generated by MPS */

import java.awt.Color;
import com.intellij.ui.JBColor;
import jetbrains.mps.nodeEditor.MPSColors;

public class IETS3Colors {
  public static Color KEYWORD = new JBColor(MPSColors.DARK_BLUE, MPSColors.LIGHT_BLUE);
  public static Color TYPE = new JBColor(new Color(0, 115, 191), new Color(0, 115, 191));
}
