package org.iets3.safety.attributes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.ConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.annotations.Nullable;

public final class LanguageConceptSwitch implements ConceptIndex {
  private final LanguageConceptIndex myIndex;
  public static final int ASILLevelAttribute = 0;
  public static final int ASILLevelValue = 1;
  public static final int AsilConstraints = 2;
  public static final int ControllabilityValue = 3;
  public static final int ExposureValue = 4;
  public static final int SeverityValue = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3d5cb9202b5f4dcbL, 0x834968b4bf077e63L);
    builder.put(0x3ce7d4897445a3bbL, ASILLevelAttribute);
    builder.put(0x1b5a6519ee9e81e2L, ASILLevelValue);
    builder.put(0x3cd510b39c56e629L, AsilConstraints);
    builder.put(0x710b4f5487c7a15dL, ControllabilityValue);
    builder.put(0x710b4f5487c7a132L, ExposureValue);
    builder.put(0x710b4f5487c7a12dL, SeverityValue);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  @Override
  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }

  @Override
  public int index(@Nullable SAbstractConcept c, int missingValue) {
    return myIndex.index(c, missingValue);
  }
}
