package org.iets3.core.expr.natlang.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import de.slisson.mps.richtext.behavior.Text__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class NatLangFunctionCall__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x64e7917630a14836L, 0x821cbf62ff6c6091L, 0x1781e8556af254ecL, "org.iets3.core.expr.natlang.structure.NatLangFunctionCall");

  public static final SMethod<Void> init_id1u1U5lEZM8a = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("init").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(1693890388432986634L).languageId(0x821cbf62ff6c6091L, 0x64e7917630a14836L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<String> renderReadable_id6kR0qIbI2yi = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("renderReadable").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7293299957844945042L).languageId(0xb66a309a6e1a7290L, 0xcfaa4966b7d54b69L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(init_id1u1U5lEZM8a, renderReadable_id6kR0qIbI2yi);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static void init_id1u1U5lEZM8a(@NotNull SNode __thisNode__, SNode fl) {
    ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.args$U5u9)).clear();
    ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.args$U5u9)).addSequence(ListSequence.fromList(SLinkOperations.getChildren(fl, LINKS.args$XOIh)).tailListSequence(1).select((it) -> {
      SNode arg = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x64e7917630a14836L, 0x821cbf62ff6c6091L, 0x1781e8556aff1984L, "org.iets3.core.expr.natlang.structure.NatLangArgument"));
      SLinkOperations.setTarget(arg, LINKS.param$UywN, it);
      return arg;
    }));
  }
  /*package*/ static String renderReadable_id6kR0qIbI2yi(@NotNull SNode __thisNode__) {
    return (String) Text__BehaviorDescriptor.asTextString_id3Q5enzfMT4l.invoke(SLinkOperations.getTarget(new IAttributeDescriptor.NodeAttribute(CONCEPTS.NatLangCallSyntax$tE).get(SLinkOperations.getTarget(__thisNode__, LINKS.extFun$6wA$)), LINKS.syntax$HiNX));
  }

  /*package*/ NatLangFunctionCall__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        init_id1u1U5lEZM8a(node, (SNode) parameters[0]);
        return null;
      case 1:
        return (T) ((String) renderReadable_id6kR0qIbI2yi(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink args$U5u9 = MetaAdapterFactory.getContainmentLink(0x64e7917630a14836L, 0x821cbf62ff6c6091L, 0x1781e8556af254ecL, 0x27b717d14a903157L, "args");
    /*package*/ static final SContainmentLink args$XOIh = MetaAdapterFactory.getContainmentLink(0x9464fa065ab9409bL, 0x927464ab29588457L, 0x427ce523083b8a2fL, 0x427ce523083b8a3fL, "args");
    /*package*/ static final SReferenceLink param$UywN = MetaAdapterFactory.getReferenceLink(0x64e7917630a14836L, 0x821cbf62ff6c6091L, 0x1781e8556aff1984L, 0x1781e8556aff199aL, "param");
    /*package*/ static final SReferenceLink extFun$6wA$ = MetaAdapterFactory.getReferenceLink(0x64e7917630a14836L, 0x821cbf62ff6c6091L, 0x1781e8556af254ecL, 0x27b717d14a8f82e8L, "extFun");
    /*package*/ static final SContainmentLink syntax$HiNX = MetaAdapterFactory.getContainmentLink(0x64e7917630a14836L, 0x821cbf62ff6c6091L, 0x1781e8556ae7b419L, 0x1781e8556ae7b4deL, "syntax");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept NatLangCallSyntax$tE = MetaAdapterFactory.getConcept(0x64e7917630a14836L, 0x821cbf62ff6c6091L, 0x1781e8556ae7b419L, "org.iets3.core.expr.natlang.structure.NatLangCallSyntax");
  }
}
