package org.iets3.core.expr.datetime.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  @Nullable
  public ConstraintsDescriptor getConstraints(@NotNull SAbstractConcept concept, @NotNull ConstraintsDescriptorInitContext context) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new AbstractCountOp_Constraints(context);
      case 1:
        return new DateDeltaToNumberOp_Constraints(context);
      case 2:
        return new DateLiteral_Constraints(context);
      case 3:
        return new DateOp_Constraints(context);
      case 4:
        return new DiscreteDateRangeOp_Constraints(context);
      case 5:
        return new MonthRangeLiteral_Constraints(context);
      case 6:
        return new MonthRangeYearOp_Constraints(context);
      case 7:
        return new PeriodRangeOp_Constraints(context);
      case 8:
        return new TimeDeltaToNumberOp_Constraints(context);
      case 9:
        return new TimeLiteral_Constraints(context);
      case 10:
        return new TimeOp_Constraints(context);
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x7511add9eda14259L), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x4ec0ae75f0bb110dL), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x35ec8ca87adca111L), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x72b77efdaa3e715dL), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x35ec8ca87af7aeeaL), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x1c99182675015cb6L), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x72b77efdaa439abdL), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x7511add9edbdd25dL), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x3b52b7f3a26f9938L), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x3b52b7f3a2255e8aL), MetaIdFactory.conceptId(0x289fb12b7f534ef7L, 0xbc2e1ed2c6a7c998L, 0x3b52b7f3a2319c70L)).seal();
}
