package org.iets3.core.base.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class OptionalNameSpecifier_Constraints extends BaseConstraintsDescriptor {
  /*package*/ OptionalNameSpecifier_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.OptionalNameSpecifier$3X, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept OptionalNameSpecifier$3X = MetaAdapterFactory.getConcept(0x7b68d745a7b848b9L, 0xbd9c05c0f8725a35L, 0x32f64a31a10020aL, "org.iets3.core.base.structure.OptionalNameSpecifier");
  }
}
