package org.iets3.core.expr.typetags.physunits.scripts;

/*Generated by MPS */

import jetbrains.mps.lang.script.runtime.BaseMigrationScript;
import jetbrains.mps.lang.script.runtime.AbstractMigrationRefactoring;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.model.SNodeReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public final class ReplaceMuWithMicroInUnitPrefixes_MigrationScript extends BaseMigrationScript {
  public ReplaceMuWithMicroInUnitPrefixes_MigrationScript() {
    super("Replace 'mu' in unit prefixes with 'micro sign'");
    this.addRefactoring(new AbstractMigrationRefactoring() {
      @Override
      public String getName() {
        return "Replace 'mu' in unit prefixes with 'micro sign'";
      }
      @Override
      public String getAdditionalInfo() {
        return "Replace 'mu' in unit prefixes with 'micro sign'";
      }
      @Override
      public SAbstractConcept getApplicableConcept() {
        return CONCEPTS.UnitReference$Zo;
      }
      @Override
      public boolean isApplicableInstanceNode(SNode node) {
        return SPropertyOperations.getString(node, PROPS.prefix$AtV).contains("\u03bc");
      }
      @Override
      public void doUpdateInstanceNode(SNode node) {
        SPropertyOperations.assign(node, PROPS.prefix$AtV, SPropertyOperations.getString(node, PROPS.prefix$AtV).replace('\u03bc', '\u00b5'));
      }
      @Override
      public boolean isShowAsIntention() {
        return false;
      }
    });
  }

  @Nullable
  @Override
  public SNodeReference getScriptNode() {
    return PersistenceFacade.getInstance().createNodeReference("r:531014dc-62ca-45fa-b1c2-cf992369440b(org.iets3.core.expr.typetags.physunits.scripts)/6252521573649140294");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept UnitReference$Zo = MetaAdapterFactory.getConcept(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d4dc5L, "org.iets3.core.expr.typetags.physunits.structure.UnitReference");
  }

  private static final class PROPS {
    /*package*/ static final SProperty prefix$AtV = MetaAdapterFactory.getProperty(0x7ee265bd59864709L, 0x86ed2c6daa33cd8cL, 0x73b48a125b0d4dc5L, 0x79d6409d1866689aL, "prefix");
  }
}
