package org.iets3.core.expr.util.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import com.mbeddr.mpsutil.treenotation.runtime.TreeCell;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import com.mbeddr.mpsutil.treenotation.runtime.IDeleteHandler;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.List;
import com.mbeddr.mpsutil.treenotation.runtime.IInsertHandler;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import com.mbeddr.mpsutil.treenotation.runtime.AbstractInsertHandler;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.editor.cells.EditorCell_Collection;
import com.mbeddr.mpsutil.grammarcells.runtime.SideTransformationHolderCell;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import com.mbeddr.mpsutil.grammarcells.runtime.CellActionWithReadAccess;
import com.mbeddr.mpsutil.grammarcells.runtime.SavedCaretPosition;
import com.mbeddr.mpsutil.grammarcells.runtime.DelegateToParentCellAction;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.editor.runtime.impl.cellActions.CellAction_DeleteSmart;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SEmptyContainmentSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.openapi.editor.menus.transformation.SNodeLocation;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.transformation.TransformationMenuItem;
import jetbrains.mps.openapi.editor.menus.transformation.TransformationMenuContext;
import com.mbeddr.mpsutil.grammarcells.runtime.StringOrSequenceQuery;
import com.mbeddr.mpsutil.grammarcells.runtime.MultiTextActionItem;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

/*package*/ class RootTreeNode_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public RootTreeNode_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createTreeCell_1();
  }

  private EditorCell createTreeCell_0(EditorContext editorContext, SNode node) {
    TreeCell editorCell = new TreeCell(editorContext, node);
    editorCell.setCellId("TreeCell_sbblmt_a");
    editorCell.setBig(true);
    setCellContext(editorCell);
    Style style = new StyleImpl();
    style.set(StyleAttributes.getInstance().<Integer>getAttribute("com.mbeddr.mpsutil.treenotation.styles", "tree-level-spacing"), _StyleParameter_QueryFunction_sbblmt_a0a());
    style.set(StyleAttributes.getInstance().<Boolean>getAttribute("com.mbeddr.mpsutil.treenotation.styles", "tree-left-to-right"), _StyleParameter_QueryFunction_sbblmt_a1a());
    editorCell.getStyle().putAll(style);
    editorCell.setTreeRoot(createSideTransformationHolderProcessor_0());
    {
      boolean showChildren = true;
      showChildren = nodeCondition_sbblmt_a0a();
      if (showChildren) {
        editorCell.setTreeChildren(createRefNodeList_0());
      }
    }
    editorCell.setDeleteHandler(new IDeleteHandler() {
      @Override
      public void delete(final EditorContext editorContext, final SNode node) {
        SNodeOperations.deleteNode(myNode);
      }
    });
    List<IInsertHandler> insertHandlers = ListSequence.fromList(new ArrayList<IInsertHandler>());
    ListSequence.fromList(insertHandlers).addElement(new AbstractInsertHandler() {
      @Override
      public void insert(final EditorContext editorContext, final SNode node, final int index) {
        ListSequence.fromList(SLinkOperations.getChildren(myNode, LINKS.children$7gtX)).insertElement(index, SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8bb1251eeae547abL, 0x984333adfae8edaaL, 0x20915a50242c7320L, "org.iets3.core.expr.util.structure.DecTreeNode")));
      }
    });
    editorCell.setInsertHandlers(insertHandlers);

    return editorCell;
  }
  private EditorCell createTreeCell_1() {
    return createTreeCell_0(getEditorContext(), myNode);
  }
  private EditorCell createSideTransformationHolderProcessor_0() {
    final EditorCell editorCell = createCollection_0();
    if (editorCell instanceof EditorCell_Collection) {
      SideTransformationHolderCell.processParentCollection((EditorCell_Collection) editorCell);
    }
    return editorCell;
  }
  private EditorCell createCollection_0() {
    jetbrains.mps.nodeEditor.cells.EditorCell_Collection editorCell = new jetbrains.mps.nodeEditor.cells.EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_sbblmt_a0a");
    editorCell.addEditorCell(createConstant_0());
    editorCell.addEditorCell(createAlternation_0());
    return editorCell;
  }
  private EditorCell createConstant_0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "<>");
    editorCell.setCellId("Constant_sbblmt_a0a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createAlternation_0() {
    boolean alternationCondition = true;
    alternationCondition = nodeCondition_sbblmt_a1a0a();
    EditorCell editorCell = null;
    if (alternationCondition) {
      editorCell = createCustomFactory_1();
    } else {
      editorCell = createSideTransformationSectionCell_0();
    }
    return editorCell;
  }
  private boolean nodeCondition_sbblmt_a1a0a() {
    return Sequence.fromIterable(AttributeOperations.getChildNodesAndAttributes(myNode, LINKS.defaultValue$Bq0p)).isNotEmpty();
  }
  private EditorCell createCustomFactory_0(final EditorContext editorContext, final SNode node) {


    final EditorCell cell = createCustomFactory_3();
    EditorCell editorCell = ((_FunctionTypes._return_P0_E0<EditorCell>) () -> {
      cell.setAction(CellActionType.BACKSPACE, new CellActionWithReadAccess() {
        public void execute(EditorContext editorContext) {
          SavedCaretPosition caretPosition = new SavedCaretPosition(editorContext);
          caretPosition.save();
          SNodeOperations.deleteNode(SLinkOperations.getTarget(node, LINKS.defaultValue$Bq0p));
          editorContext.flushEvents();
          caretPosition.restore(true);
        }
      });
      cell.setAction(CellActionType.DELETE, new CellActionWithReadAccess() {
        public void execute(EditorContext editorContext) {
          SavedCaretPosition caretPosition = new SavedCaretPosition(editorContext);
          caretPosition.save();
          SNodeOperations.deleteNode(SLinkOperations.getTarget(node, LINKS.defaultValue$Bq0p));
          editorContext.flushEvents();
          caretPosition.restore(false);
        }
      });
      return cell;
    }).invoke();
    return editorCell;
  }
  private EditorCell createCustomFactory_1() {
    return createCustomFactory_0(getEditorContext(), myNode);
  }
  private EditorCell createCustomFactory_2(final EditorContext editorContext, final SNode node) {


    final EditorCell cell = createCollection_1();
    EditorCell editorCell = ((_FunctionTypes._return_P0_E0<EditorCell>) () -> {
      final SNode childNode = SLinkOperations.getTarget(myNode, LINKS.defaultValue$Bq0p);
      new Object() {
        public void removeDeleteAction(EditorCell descendantCell) {
          if (descendantCell.getSNode() == childNode) {
            descendantCell.setAction(CellActionType.DELETE, new DelegateToParentCellAction(descendantCell, CellActionType.DELETE));
            descendantCell.setAction(CellActionType.BACKSPACE, new DelegateToParentCellAction(descendantCell, CellActionType.BACKSPACE));
          } else {
            if (descendantCell instanceof EditorCell_Collection) {
              for (EditorCell childCell : Sequence.fromIterable(((EditorCell_Collection) descendantCell))) {
                removeDeleteAction(childCell);
              }
            }
          }
        }
      }.removeDeleteAction(cell);
      return cell;
    }).invoke();
    return editorCell;
  }
  private EditorCell createCustomFactory_3() {
    return createCustomFactory_2(getEditorContext(), myNode);
  }
  private EditorCell createCollection_1() {
    jetbrains.mps.nodeEditor.cells.EditorCell_Collection editorCell = new jetbrains.mps.nodeEditor.cells.EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_sbblmt_a0a1a0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createConstant_1());
    editorCell.addEditorCell(createRefNode_0());
    return editorCell;
  }
  private EditorCell createConstant_1() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "default:");
    editorCell.setCellId("Constant_sbblmt_a0a0b0a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_0() {
    SingleRoleCellProvider provider = new defaultValueSingleRoleHandler_sbblmt_b0a0b0a0(myNode, LINKS.defaultValue$Bq0p, getEditorContext());
    return provider.createCell();
  }
  private static class defaultValueSingleRoleHandler_sbblmt_b0a0b0a0 extends SingleRoleCellProvider {
    @NotNull
    private SNode myNode;

    public defaultValueSingleRoleHandler_sbblmt_b0a0b0a0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(containmentLink, context);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = getUpdateSession().updateChildNodeCell(child);
      editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(getNode(), LINKS.defaultValue$Bq0p, child));
      editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(getNode(), LINKS.defaultValue$Bq0p, child));
      installCellInfo(child, editorCell, false);
      return editorCell;
    }



    private void installCellInfo(SNode child, EditorCell editorCell, boolean isEmpty) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo((isEmpty ? new SEmptyContainmentSubstituteInfo(editorCell) : new SChildSubstituteInfo(editorCell)));
      }
      if (editorCell.getSRole() == null) {
        editorCell.setSRole(LINKS.defaultValue$Bq0p);
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(getNode(), LINKS.defaultValue$Bq0p));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_defaultValue");
        installCellInfo(null, editorCell, true);
        setCellContext(editorCell);
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no defaultValue>";
    }
  }
  private EditorCell createSideTransformationSectionCell_0() {
    SideTransformationHolderCell editorCell = new SideTransformationHolderCell(getEditorContext(), myNode, null, "grammar.optional for RootTreeNode.defaultValue") {
      @Override
      public List<MenuPart<TransformationMenuItem, TransformationMenuContext>> createMenuParts() {
        return ListSequence.fromListAndArray(new ArrayList<MenuPart<TransformationMenuItem, TransformationMenuContext>>(), new GenericMenuPart_a0a1a0a());
      }
    };
    editorCell.setCellId("SideTransformationSectionCell_sbblmt_a1a0a");
    return editorCell;
  }
  private class GenericMenuPart_a0a1a0a implements MenuPart<TransformationMenuItem, TransformationMenuContext> {

    @NotNull
    @Override
    public List<TransformationMenuItem> createItems(final TransformationMenuContext ctx) {
      List<TransformationMenuItem> result = ListSequence.fromList(new ArrayList<TransformationMenuItem>());
      final SNode sourceNode = ctx.getNode();
      EditorContext editorContext = ctx.getEditorContext();
      final Iterable<String> matchingTexts = new StringOrSequenceQuery() {
        public Object queryStringOrSequence() {
          return Sequence.<String>singleton("default:");
        }
      }.query();

      if (Sequence.fromIterable(matchingTexts).isNotEmpty()) {
        ListSequence.fromList(result).addElement(new MultiTextActionItem(matchingTexts, ctx) {
          @Override
          public void execute(@NotNull String pattern) {
            final SNode sourceNode = ctx.getNode();
            EditorContext editorContext = ctx.getEditorContext();
            SNode newNode = SNodeFactoryOperations.setNewChild(SNodeOperations.cast(sourceNode, CONCEPTS.RootTreeNode$nS), LINKS.defaultValue$Bq0p, null);
          }
          @Override
          public SAbstractConcept getOutputConcept() {
            return CONCEPTS.RootTreeNode$nS;
          }

          @Nullable
          @Override
          public String getShortDescriptionText(@NotNull String pattern) {
            SNode node = ctx.getNode();
            String originalText = super.getShortDescriptionText(pattern);
            EditorContext editorContext = ctx.getEditorContext();
            return "a default value for the root tree node";
          }
        });
      }
      return result;
    }
  }
  private EditorCell createRefNodeList_0() {
    AbstractCellListHandler handler = new childrenListHandler_sbblmt_a0(myNode, getEditorContext());
    jetbrains.mps.nodeEditor.cells.EditorCell_Collection editorCell = handler.createCells(new CellLayout_Horizontal(), false);
    editorCell.setCellId("refNodeList_children");
    editorCell.setSRole(handler.getElementSRole());
    return editorCell;
  }
  private static class childrenListHandler_sbblmt_a0 extends RefNodeListHandler {
    @NotNull
    private SNode myNode;

    public childrenListHandler_sbblmt_a0(SNode ownerNode, EditorContext context) {
      super(context, false);
      myNode = ownerNode;
    }

    @NotNull
    public SNode getNode() {
      return myNode;
    }
    public SContainmentLink getSLink() {
      return LINKS.children$7gtX;
    }
    public SAbstractConcept getChildSConcept() {
      return CONCEPTS.DecTreeNode$r$;
    }

    public EditorCell createNodeCell(SNode elementNode) {
      EditorCell elementCell = getUpdateSession().updateChildNodeCell(elementNode);
      installElementCellActions(elementNode, elementCell, false);
      return elementCell;
    }
    public EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(childrenListHandler_sbblmt_a0.this.getNode(), LINKS.children$7gtX));
      try {
        EditorCell emptyCell = null;
        emptyCell = super.createEmptyCell();
        installElementCellActions(null, emptyCell, true);
        setCellContext(emptyCell);
        return emptyCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }

    private static final Object OBJ = new Object();

    public void installElementCellActions(SNode elementNode, EditorCell elementCell, boolean isEmptyCell) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_COMPLETE_SET) == null) {
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_COMPLETE_SET, OBJ);
          elementCell.setSubstituteInfo((isEmptyCell ? new SEmptyContainmentSubstituteInfo(elementCell) : new SChildSubstituteInfo(elementCell)));
        }
      }
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_DELETE_SET) == null) {
        if (elementNode != null) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_DELETE_SET, OBJ);
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.FORWARD));
        }
      }
      if (elementCell.getUserObject(ELEMENT_CELL_BACKSPACE_SET) == null) {
        if (elementNode != null) {
          elementCell.putUserObject(ELEMENT_CELL_BACKSPACE_SET, OBJ);
          elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.BACKWARD));
        }
      }
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        if (elementNode != null) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, OBJ);
        }
      }
    }
  }
  private boolean nodeCondition_sbblmt_a0a() {
    return ListSequence.fromList(SLinkOperations.getChildren(myNode, LINKS.children$7gtX)).isNotEmpty();
  }
  private int _StyleParameter_QueryFunction_sbblmt_a0a() {
    return 40;
  }
  private boolean _StyleParameter_QueryFunction_sbblmt_a1a() {
    return SPropertyOperations.getBoolean(SNodeOperations.getNodeAncestor(getNode(), CONCEPTS.DecTree$r5, false, false), PROPS.horizontal$TtLt);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink children$7gtX = MetaAdapterFactory.getContainmentLink(0x8bb1251eeae547abL, 0x984333adfae8edaaL, 0x83c0947ee7c65f8L, 0x20915a50242c7675L, "children");
    /*package*/ static final SContainmentLink defaultValue$Bq0p = MetaAdapterFactory.getContainmentLink(0x8bb1251eeae547abL, 0x984333adfae8edaaL, 0x83c0947ee7cd282L, 0x1cf7e807cc4bfed6L, "defaultValue");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept RootTreeNode$nS = MetaAdapterFactory.getConcept(0x8bb1251eeae547abL, 0x984333adfae8edaaL, 0x83c0947ee7cd282L, "org.iets3.core.expr.util.structure.RootTreeNode");
    /*package*/ static final SConcept DecTreeNode$r$ = MetaAdapterFactory.getConcept(0x8bb1251eeae547abL, 0x984333adfae8edaaL, 0x20915a50242c7320L, "org.iets3.core.expr.util.structure.DecTreeNode");
    /*package*/ static final SConcept DecTree$r5 = MetaAdapterFactory.getConcept(0x8bb1251eeae547abL, 0x984333adfae8edaaL, 0x20915a50242c731fL, "org.iets3.core.expr.util.structure.DecTree");
  }

  private static final class PROPS {
    /*package*/ static final SProperty horizontal$TtLt = MetaAdapterFactory.getProperty(0x8bb1251eeae547abL, 0x984333adfae8edaaL, 0x20915a50242c731fL, 0x27db155db5f0d438L, "horizontal");
  }
}
