package org.iets3.core.expr.data.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class GrammarCellsSubstituteMenu_DataIsInTarget extends SubstituteMenuBase {
  public GrammarCellsSubstituteMenu_DataIsInTarget() {
    super(true, new EditorMenuDescriptorBase("contribution to the " + "default substitute menu for " + "DataIsInTarget", null));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new GrammarCellsSubstituteMenuPart_hokbtv_a());
    return result;
  }

  private class GrammarCellsSubstituteMenuPart_hokbtv_a extends GrammarCellsSubstituteMenuPart {
    @Override
    public SModule getModule(SRepository repository) {
      return PersistenceFacade.getInstance().createModuleReference("b25b8ad1-4d3d-4e45-8c78-72091b39fdda(org.iets3.core.expr.data)").resolve(repository);
    }
    @Override
    public SAbstractConcept getExpectedOutputConcept() {
      return CONCEPTS.DataIsInTarget$PR;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DataIsInTarget$PR = MetaAdapterFactory.getConcept(0xb25b8ad14d3d4e45L, 0x8c7872091b39fddaL, 0x3886d6f8346755b7L, "org.iets3.core.expr.data.structure.DataIsInTarget");
  }
}
