package org.iets3.core.expr.tracing.plugin.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconLoadingUtil;

public class IconContainer {
  protected static Icon ICON0 = IconLoadingUtil.loadIcon("/icons/traceShowAll.png", IconContainer.class);
  protected static Icon ICON1 = IconLoadingUtil.loadIcon("/icons/traceShowOne.png", IconContainer.class);
  protected static Icon ICON2 = IconLoadingUtil.loadIcon("/icons/traceShowOne.png", IconContainer.class);
  protected static Icon ICON3 = IconLoadingUtil.loadIcon("/icons/trace.png", IconContainer.class);
}
