package org.iets3.core.expr.process.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_SenderPartyInterceptor_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_SenderPartyInterceptor_NonTypesystemRule() {
  }
  public void applyRule(final SNode spi, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    SNode tt = TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(spi, LINKS.expr$CW3E));
    if (!(SNodeOperations.isInstanceOf(tt, CONCEPTS.PartyType$21) || SNodeOperations.isInstanceOf(tt, CONCEPTS.CollectionType$kS) && SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SNodeOperations.cast(tt, CONCEPTS.CollectionType$kS), LINKS.baseType$5NOJ), CONCEPTS.PartyType$21))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(spi, LINKS.expr$CW3E), "party or collection of parties required", "r:f58f4a3c-02d7-4cfe-abe9-c107d957e34d(org.iets3.core.expr.process.typesystem)", "5456956546144091821", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.SenderPartyInterceptor$bV;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expr$CW3E = MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x3b256bb6ae8048d8L, 0x3b256bb6ae8048d9L, "expr");
    /*package*/ static final SContainmentLink baseType$5NOJ = MetaAdapterFactory.getContainmentLink(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x68d69d36ba495885L, 0x68d69d36ba495886L, "baseType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PartyType$21 = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0xfc43d48233b0f22L, "org.iets3.core.expr.process.structure.PartyType");
    /*package*/ static final SConcept CollectionType$kS = MetaAdapterFactory.getConcept(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x68d69d36ba495885L, "org.iets3.core.expr.collections.structure.CollectionType");
    /*package*/ static final SConcept SenderPartyInterceptor$bV = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x4bbb011107a8a488L, "org.iets3.core.expr.process.structure.SenderPartyInterceptor");
  }
}
