package org.iets3.core.expr.process.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class check_TakeTurnsInterceptor_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_TakeTurnsInterceptor_NonTypesystemRule() {
  }
  public void applyRule(final SNode tti, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SPropertyOperations.getBoolean(tti, PROPS.ordered$aTT_)) {
      if (!(SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(tti, LINKS.expr$CW3E)), CONCEPTS.ListType$i0) && SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SNodeOperations.cast(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(tti, LINKS.expr$CW3E)), CONCEPTS.ListType$i0), LINKS.baseType$5NOJ), CONCEPTS.PartyType$21))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(tti, LINKS.expr$CW3E), "expecting an ordered list of parties", "r:f58f4a3c-02d7-4cfe-abe9-c107d957e34d(org.iets3.core.expr.process.typesystem)", "5456956546156301704", null, errorTarget);
        }
      }
    } else {
      if (!(SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(tti, LINKS.expr$CW3E)), CONCEPTS.CollectionType$kS) && SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SNodeOperations.cast(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(tti, LINKS.expr$CW3E)), CONCEPTS.CollectionType$kS), LINKS.baseType$5NOJ), CONCEPTS.PartyType$21))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(tti, LINKS.expr$CW3E), "expecting a collection of parties", "r:f58f4a3c-02d7-4cfe-abe9-c107d957e34d(org.iets3.core.expr.process.typesystem)", "5456956546155609247", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.TakeTurnsInterceptor$2m;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expr$CW3E = MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x3b256bb6ae8048d8L, 0x3b256bb6ae8048d9L, "expr");
    /*package*/ static final SContainmentLink baseType$5NOJ = MetaAdapterFactory.getContainmentLink(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x68d69d36ba495885L, 0x68d69d36ba495886L, "baseType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ListType$i0 = MetaAdapterFactory.getConcept(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x68d69d36ba497720L, "org.iets3.core.expr.collections.structure.ListType");
    /*package*/ static final SConcept PartyType$21 = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0xfc43d48233b0f22L, "org.iets3.core.expr.process.structure.PartyType");
    /*package*/ static final SConcept CollectionType$kS = MetaAdapterFactory.getConcept(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x68d69d36ba495885L, "org.iets3.core.expr.collections.structure.CollectionType");
    /*package*/ static final SConcept TakeTurnsInterceptor$2m = MetaAdapterFactory.getConcept(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x4bbb01110854f1ddL, "org.iets3.core.expr.process.structure.TakeTurnsInterceptor");
  }

  private static final class PROPS {
    /*package*/ static final SProperty ordered$aTT_ = MetaAdapterFactory.getProperty(0x50b470e714ad46c3L, 0xb5404586f56d2e9cL, 0x4bbb01110854f1ddL, 0x4bbb01110854f24eL, "ordered");
  }
}
