package org.iets3.core.expr.mutable.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_BoxExpression_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_BoxExpression_InferenceRule() {
  }
  public void applyRule(final SNode be, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final SNode valueType = typeCheckingContext.typeOf(SLinkOperations.getTarget(be, LINKS.expr$CW3E), "r:a71eb8ca-1a88-4b3c-85ef-63f23e5a12e0(org.iets3.core.expr.mutable.typesystem)", "4255172619710743205", true);
      typeCheckingContext.whenConcrete(valueType, () -> {
        {
          SNode _nodeToCheck_1029348928467 = be;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:a71eb8ca-1a88-4b3c-85ef-63f23e5a12e0(org.iets3.core.expr.mutable.typesystem)", "4255172619710741571", 0, null);
          typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:a71eb8ca-1a88-4b3c-85ef-63f23e5a12e0(org.iets3.core.expr.mutable.typesystem)", "4255172619710740643", true), (SNode) createBoxType_nyrusl_a1a0c0a0b0a1a0a1(SNodeOperations.cast(SNodeOperations.copyNode(typeCheckingContext.getExpandedNode(valueType)), CONCEPTS.Type$WK)), _info_12389875345);
        }
      }, "r:a71eb8ca-1a88-4b3c-85ef-63f23e5a12e0(org.iets3.core.expr.mutable.typesystem)", "4255172619710743147", false, false);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.BoxExpression$VK;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static SNode createBoxType_nyrusl_a1a0c0a0b0a1a0a1(SNode p0) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.BoxType$Bc);
    n0.forChild(LINKS.baseType$ofMQ).initNode(p0, CONCEPTS.Type$WK, true);
    return n0.getResult();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expr$CW3E = MetaAdapterFactory.getContainmentLink(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x3b256bb6ae8048d8L, 0x3b256bb6ae8048d9L, "expr");
    /*package*/ static final SContainmentLink baseType$ofMQ = MetaAdapterFactory.getContainmentLink(0xfbba51185fc649ffL, 0x9c3b0b4469830440L, 0x3b0d68f3e7c18996L, 0x3b0d68f3e7c18997L, "baseType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Type$WK = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x670d5e92f854a614L, "org.iets3.core.expr.base.structure.Type");
    /*package*/ static final SConcept BoxExpression$VK = MetaAdapterFactory.getConcept(0xfbba51185fc649ffL, 0x9c3b0b4469830440L, 0x3b0d68f3e7d3b81eL, "org.iets3.core.expr.mutable.structure.BoxExpression");
    /*package*/ static final SConcept BoxType$Bc = MetaAdapterFactory.getConcept(0xfbba51185fc649ffL, 0x9c3b0b4469830440L, 0x3b0d68f3e7c18996L, "org.iets3.core.expr.mutable.structure.BoxType");
  }
}
