package org.iets3.core.expr.collections.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import org.iets3.core.expr.base.behavior.IDotTarget__BehaviorDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class FoldOp__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x4471391c39ffd310L, "org.iets3.core.expr.collections.structure.FoldOp");

  public static final SMethod<String> renderReadable_id6kR0qIbI2yi = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("renderReadable").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7293299957844945042L).languageId(0xb66a309a6e1a7290L, 0xcfaa4966b7d54b69L).build2();
  public static final SMethod<Boolean> checkCombinerIsFunctionType_id4hLehKU5pi7 = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("checkCombinerIsFunctionType").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4931785860343764103L).languageId(0x9fa52465d68f5996L, 0x2f7e2e356e744c43L).build2();
  public static final SMethod<Void> fixCombinerFunctionType_id4hLehKU5tgW = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("fixCombinerFunctionType").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4931785860343780412L).languageId(0x9fa52465d68f5996L, 0x2f7e2e356e744c43L).build2();
  public static final SMethod<String> allowsEffectForNode_idORfz$DS6Ap = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("allowsEffectForNode").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(952298261448780185L).languageId(0xb66a309a6e1a7290L, 0xcfaa4966b7d54b69L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(renderReadable_id6kR0qIbI2yi, checkCombinerIsFunctionType_id4hLehKU5pi7, fixCombinerFunctionType_id4hLehKU5tgW, allowsEffectForNode_idORfz$DS6Ap);

  private static void ___init___(@NotNull SNode __thisNode__) {
    FoldOp__BehaviorDescriptor.fixCombinerFunctionType_id4hLehKU5tgW.invoke(__thisNode__);
  }

  /*package*/ static String renderReadable_id6kR0qIbI2yi(@NotNull SNode __thisNode__) {
    return SConceptOperations.conceptAlias(SNodeOperations.getConcept(__thisNode__)) + "(" + BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.seed$l9w1)) + ", " + BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.combiner$lad4)) + ")";
  }
  /*package*/ static boolean checkCombinerIsFunctionType_id4hLehKU5pi7(@NotNull SNode __thisNode__) {
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(SLinkOperations.getTarget(__thisNode__, LINKS.combiner$lad4))), CONCEPTS.Expression$D_)) {
      return false;
    }
    return SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(__thisNode__, LINKS.combiner$lad4)), CONCEPTS.FunctionType$RQ);
  }
  /*package*/ static void fixCombinerFunctionType_id4hLehKU5tgW(@NotNull SNode __thisNode__) {
    SNode prevExpression = SLinkOperations.getTarget(__thisNode__, LINKS.combiner$lad4);
    SNode elementType = IDotTarget__BehaviorDescriptor.extractContextBaseType_id5WNmJ7DoWfr.invoke(__thisNode__);
    SNode seedType = SNodeOperations.cast(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(__thisNode__, LINKS.seed$l9w1)), CONCEPTS.Type$WK);
    SNode lambda = createLambdaExpression_c6pv6f_a0d0c(SNodeOperations.copyNode(seedType), SNodeOperations.copyNode(elementType), prevExpression);
    SLinkOperations.setTarget(__thisNode__, LINKS.combiner$lad4, lambda);
  }
  /*package*/ static String allowsEffectForNode_idORfz$DS6Ap(@NotNull SNode __thisNode__, SNode n) {
    return "no effects are allowed in fold";
  }

  /*package*/ FoldOp__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) renderReadable_id6kR0qIbI2yi(node));
      case 1:
        return (T) ((Boolean) checkCombinerIsFunctionType_id4hLehKU5pi7(node));
      case 2:
        fixCombinerFunctionType_id4hLehKU5tgW(node);
        return null;
      case 3:
        return (T) ((String) allowsEffectForNode_idORfz$DS6Ap(node, (SNode) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
  private static SNode createLambdaExpression_c6pv6f_a0d0c(SNode p0, SNode p1, SNode p2) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.LambdaExpression$64);
    {
      SNodeBuilder n1 = n0.forChild(LINKS.args$8wKH).init(CONCEPTS.LambdaArg$9W);
      n1.setProperty(PROPS.name$MnvL, "seed");
      n1.forChild(LINKS.type$8xXf).initNode(p0, CONCEPTS.Type$WK, true);
      SNodeBuilder n2 = n1.forSibling().init(CONCEPTS.LambdaArg$9W);
      n2.setProperty(PROPS.name$MnvL, "current");
      n2.forChild(LINKS.type$8xXf).initNode(p1, CONCEPTS.Type$WK, true);
    }
    n0.forChild(LINKS.expression$T2aj).initNode(p2, CONCEPTS.Expression$D_, true);
    return n0.getResult();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink seed$l9w1 = MetaAdapterFactory.getContainmentLink(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x4471391c39ffd310L, 0x4471391c3a005345L, "seed");
    /*package*/ static final SContainmentLink combiner$lad4 = MetaAdapterFactory.getContainmentLink(0x2f7e2e356e744c43L, 0x9fa52465d68f5996L, 0x4471391c39ffd310L, 0x4471391c3a005348L, "combiner");
    /*package*/ static final SContainmentLink args$8wKH = MetaAdapterFactory.getContainmentLink(0x9464fa065ab9409bL, 0x927464ab29588457L, 0x68d69d36ba520706L, 0x68d69d36ba520707L, "args");
    /*package*/ static final SContainmentLink type$8xXf = MetaAdapterFactory.getContainmentLink(0x9464fa065ab9409bL, 0x927464ab29588457L, 0x68d69d36ba520709L, 0x68d69d36ba52070cL, "type");
    /*package*/ static final SContainmentLink expression$T2aj = MetaAdapterFactory.getContainmentLink(0x9464fa065ab9409bL, 0x927464ab29588457L, 0x68d69d36ba520706L, 0x68d69d36ba520b43L, "expression");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Expression$D_ = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x670d5e92f854a047L, "org.iets3.core.expr.base.structure.Expression");
    /*package*/ static final SConcept FunctionType$RQ = MetaAdapterFactory.getConcept(0x9464fa065ab9409bL, 0x927464ab29588457L, 0x68d69d36ba4ecfb6L, "org.iets3.core.expr.lambda.structure.FunctionType");
    /*package*/ static final SConcept Type$WK = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x670d5e92f854a614L, "org.iets3.core.expr.base.structure.Type");
    /*package*/ static final SConcept LambdaExpression$64 = MetaAdapterFactory.getConcept(0x9464fa065ab9409bL, 0x927464ab29588457L, 0x68d69d36ba520706L, "org.iets3.core.expr.lambda.structure.LambdaExpression");
    /*package*/ static final SConcept LambdaArg$9W = MetaAdapterFactory.getConcept(0x9464fa065ab9409bL, 0x927464ab29588457L, 0x68d69d36ba52070eL, "org.iets3.core.expr.lambda.structure.LambdaArg");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
