package org.iets3.variability.artifacts.base.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.iets3.core.expr.base.behavior.Expression__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class FeatureDecTabContent__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xf08835038eaa4bc8L, 0x8846eb63220ab1ddL, 0x2de0d5b2023d497bL, "org.iets3.variability.artifacts.base.structure.FeatureDecTabContent");

  public static final SMethod<String> getPresentation_idhEwIMiw = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getPresentation").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(1213877396640L).languageId(0x9b92103b95ca8c0cL, 0xceab519525ea4f22L).build2();
  public static final SMethod<String> nameForSolver_id3q2wVeozeaM = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("nameForSolver").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3927846632402248370L).languageId(0x8846eb63220ab1ddL, 0xf08835038eaa4bc8L).build2();
  public static final SMethod<SNode> artifactNode_id3q2wVepCV0v = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("artifactNode").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3927846632420519967L).languageId(0x8846eb63220ab1ddL, 0xf08835038eaa4bc8L).build2();
  public static final SMethod<SNode> artifactNodeData_id3PRltoWVL10 = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("artifactNodeData").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4429103137175834688L).languageId(0x8846eb63220ab1ddL, 0xf08835038eaa4bc8L).build2();
  public static final SMethod<SNode> getContextFeature_id30ECcbtSVMe = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getContextFeature").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3470763221649177742L).languageId(0x895e1424f54166ecL, 0x165f1d0525064544L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getPresentation_idhEwIMiw, nameForSolver_id3q2wVeozeaM, artifactNode_id3q2wVepCV0v, artifactNodeData_id3PRltoWVL10, getContextFeature_id30ECcbtSVMe);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getPresentation_idhEwIMiw(@NotNull SNode __thisNode__) {
    return "FDTC(" + Expression__BehaviorDescriptor.renderReadable_id4Y0vh0cfqjE.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.featureExpr$cJRc)) + ")";
  }
  /*package*/ static String nameForSolver_id3q2wVeozeaM(@NotNull SNode __thisNode__) {
    return "FDTC_" + IVariationPointBase__BehaviorDescriptor.shortId_idqnZSGXva9v.invoke(__thisNode__, __thisNode__) + "_" + SNodeOperations.getIndexInParent(__thisNode__);
  }
  /*package*/ static SNode artifactNode_id3q2wVepCV0v(@NotNull SNode __thisNode__) {
    return __thisNode__;
  }
  /*package*/ static SNode artifactNodeData_id3PRltoWVL10(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(__thisNode__, LINKS.result$qMa$);
  }
  /*package*/ static SNode getContextFeature_id30ECcbtSVMe(@NotNull SNode __thisNode__) {
    SNode exprType = TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(__thisNode__, LINKS.featureExpr$cJRc));
    return (SNodeOperations.isInstanceOf(exprType, CONCEPTS.FeatureType$_L) ? SLinkOperations.getTarget(SNodeOperations.cast(exprType, CONCEPTS.FeatureType$_L), LINKS.feature$SwK2) : null);
  }

  /*package*/ FeatureDecTabContent__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getPresentation_idhEwIMiw(node));
      case 1:
        return (T) ((String) nameForSolver_id3q2wVeozeaM(node));
      case 2:
        return (T) ((SNode) artifactNode_id3q2wVepCV0v(node));
      case 3:
        return (T) ((SNode) artifactNodeData_id3PRltoWVL10(node));
      case 4:
        return (T) ((SNode) getContextFeature_id30ECcbtSVMe(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink featureExpr$cJRc = MetaAdapterFactory.getContainmentLink(0xf08835038eaa4bc8L, 0x8846eb63220ab1ddL, 0xe86d1af52aae5ceL, 0x55275f0cc818c452L, "featureExpr");
    /*package*/ static final SContainmentLink result$qMa$ = MetaAdapterFactory.getContainmentLink(0xf08835038eaa4bc8L, 0x8846eb63220ab1ddL, 0x2de0d5b2023d497bL, 0x2de0d5b2023d823bL, "result");
    /*package*/ static final SReferenceLink feature$SwK2 = MetaAdapterFactory.getReferenceLink(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x7cde27c7fd8487c2L, 0x7cde27c7fd8487ccL, "feature");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FeatureType$_L = MetaAdapterFactory.getConcept(0x165f1d0525064544L, 0x895e1424f54166ecL, 0x7cde27c7fd8487c2L, "org.iets3.variability.featuremodel.base.structure.FeatureType");
  }
}
