package test.in.expr.os.numbers;

/*Generated by MPS */

import org.iets3.core.expr.simpleTypes.runtime.AH;
import java.math.BigInteger;
import org.junit.Test;
import org.junit.Assert;
import org.iets3.core.expr.genjava.tests.rt.rt.EqualsTestOp;
import java.math.BigDecimal;
import java.math.RoundingMode;
import org.iets3.core.expr.genjava.tests.rt.rt.RealEqualsTestOp;

/**
 * 
 */
public class Generated_numbers_Test {

  public static final Number a1_ = AH.add(new BigInteger("10"), new BigInteger("2"));
  public static final Number a2_ = AH.add(Generated_numbers_Test.a1_, Generated_numbers_Test.a1_);
  public static final Number a3_ = new BigInteger("5");
  public static final Number a4_ = AH.add(Generated_numbers_Test.a3_, Generated_numbers_Test.a2_);
  @Test
  public void Addition_item0_9154139946178802440() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("12") + ", but was: " + Generated_numbers_Test.a1_, EqualsTestOp.matches(new BigInteger("12"), Generated_numbers_Test.a1_));
  }
  @Test
  public void Addition_item1_9154139946178821889() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("24") + ", but was: " + Generated_numbers_Test.a2_, EqualsTestOp.matches(new BigInteger("24"), Generated_numbers_Test.a2_));
  }
  @Test
  public void Addition_item2_9154139946178821922() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("5") + ", but was: " + Generated_numbers_Test.a3_, EqualsTestOp.matches(new BigInteger("5"), Generated_numbers_Test.a3_));
  }
  @Test
  public void Addition_item3_9154139946178832999() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("29") + ", but was: " + Generated_numbers_Test.a4_, EqualsTestOp.matches(new BigInteger("29"), Generated_numbers_Test.a4_));
  }
  public static final Number s1_ = AH.sub(new BigInteger("10"), new BigInteger("2"));
  public static final Number s2_ = AH.sub(Generated_numbers_Test.s1_, Generated_numbers_Test.s1_);
  public static final Number s3_ = new BigInteger("5");
  public static final Number s4_ = AH.sub(Generated_numbers_Test.s3_, Generated_numbers_Test.s2_);
  public static final Number s5_ = AH.sub(new BigInteger("10"), new BigInteger("100"));
  public static final Number s6_ = AH.sub(Generated_numbers_Test.s4_, Generated_numbers_Test.s5_);
  @Test
  public void Subtraction_item0_9154139946179049210() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("8") + ", but was: " + Generated_numbers_Test.s1_, EqualsTestOp.matches(new BigInteger("8"), Generated_numbers_Test.s1_));
  }
  @Test
  public void Subtraction_item1_9154139946179049256() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("0") + ", but was: " + Generated_numbers_Test.s2_, EqualsTestOp.matches(new BigInteger("0"), Generated_numbers_Test.s2_));
  }
  @Test
  public void Subtraction_item2_9154139946179049288() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("5") + ", but was: " + Generated_numbers_Test.s3_, EqualsTestOp.matches(new BigInteger("5"), Generated_numbers_Test.s3_));
  }
  @Test
  public void Subtraction_item3_9154139946179049324() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("5") + ", but was: " + Generated_numbers_Test.s4_, EqualsTestOp.matches(new BigInteger("5"), Generated_numbers_Test.s4_));
  }
  @Test
  public void Subtraction_item4_9154139946179049364() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("-90") + ", but was: " + Generated_numbers_Test.s5_, EqualsTestOp.matches(new BigInteger("-90"), Generated_numbers_Test.s5_));
  }
  @Test
  public void Subtraction_item5_9154139946179049408() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("95") + ", but was: " + Generated_numbers_Test.s6_, EqualsTestOp.matches(new BigInteger("95"), Generated_numbers_Test.s6_));
  }
  public static final Number m1_ = AH.mul(new BigInteger("4"), new BigInteger("4"));
  public static final Number m2_ = new BigInteger("5");
  public static final Number m3_ = AH.mul(Generated_numbers_Test.m1_, Generated_numbers_Test.m2_);
  public static final Number m4_ = new BigInteger("0");
  public static final Number m5_ = AH.mul(Generated_numbers_Test.m3_, Generated_numbers_Test.m4_);
  @Test
  public void MultiInt_item0_9154139946179104848() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("16") + ", but was: " + Generated_numbers_Test.m1_, EqualsTestOp.matches(new BigInteger("16"), Generated_numbers_Test.m1_));
  }
  @Test
  public void MultiInt_item1_9154139946179110660() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("5") + ", but was: " + Generated_numbers_Test.m2_, EqualsTestOp.matches(new BigInteger("5"), Generated_numbers_Test.m2_));
  }
  @Test
  public void MultiInt_item2_9154139946179110692() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("80") + ", but was: " + Generated_numbers_Test.m3_, EqualsTestOp.matches(new BigInteger("80"), Generated_numbers_Test.m3_));
  }
  @Test
  public void MultiInt_item3_9154139946179110728() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("0") + ", but was: " + Generated_numbers_Test.m4_, EqualsTestOp.matches(new BigInteger("0"), Generated_numbers_Test.m4_));
  }
  @Test
  public void MultiInt_item4_9154139946179110768() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("0") + ", but was: " + Generated_numbers_Test.m5_, EqualsTestOp.matches(new BigInteger("0"), Generated_numbers_Test.m5_));
  }
  public static final Number mr1_ = new BigDecimal("10.22").setScale(2, RoundingMode.DOWN);
  public static final Number mr2_ = new BigInteger("2");
  public static final Number mr3_ = AH.mul(Generated_numbers_Test.mr1_, Generated_numbers_Test.mr2_);
  public static final Number mr4_ = new BigDecimal("0.3").setScale(1, RoundingMode.DOWN);
  public static final Number mr5_ = AH.mul(Generated_numbers_Test.mr1_, Generated_numbers_Test.mr4_);
  public static final Number mr6_ = new BigDecimal("3.3333333").setScale(7, RoundingMode.DOWN);
  public static final Number mr7_ = AH.mul(Generated_numbers_Test.mr6_, new BigInteger("2"));
  @Test
  public void MultiDec_item0_9154139946179161495() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("10.22").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.mr1_, EqualsTestOp.matches(new BigDecimal("10.22").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.mr1_));
  }
  @Test
  public void MultiDec_item1_9154139946179161499() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("2") + ", but was: " + Generated_numbers_Test.mr2_, EqualsTestOp.matches(new BigInteger("2"), Generated_numbers_Test.mr2_));
  }
  @Test
  public void MultiDec_item2_9154139946179161503() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("20.44").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.mr3_, EqualsTestOp.matches(new BigDecimal("20.44").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.mr3_));
  }
  @Test
  public void MultiDec_item3_9154139946179161507() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("0.3").setScale(1, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.mr4_, EqualsTestOp.matches(new BigDecimal("0.3").setScale(1, RoundingMode.DOWN), Generated_numbers_Test.mr4_));
  }
  @Test
  public void MultiDec_item4_9154139946179161511() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("3.066").setScale(3, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.mr5_, EqualsTestOp.matches(new BigDecimal("3.066").setScale(3, RoundingMode.DOWN), Generated_numbers_Test.mr5_));
  }
  @Test
  public void MultiDec_item5_8440513089311269381() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("6.6666666000").setScale(10, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.mr7_, EqualsTestOp.matches(new BigDecimal("6.6666666000").setScale(10, RoundingMode.DOWN), Generated_numbers_Test.mr7_));
  }
  public static final Number d1_ = AH.div(new BigInteger("10"), new BigInteger("2"));
  public static final Number d2_ = new BigInteger("5");
  public static final Number d3_ = AH.div(Generated_numbers_Test.d2_, Generated_numbers_Test.d2_);
  public static final Number d4_ = AH.div(new BigInteger("5"), new BigInteger("9"));
  public static final Number d5_ = AH.div(new BigInteger("5"), new BigInteger("-9"));
  public static final Number d6_ = new BigInteger("5").negate();
  public static final Number d7_ = AH.div(Generated_numbers_Test.d6_, Generated_numbers_Test.d2_);
  public static final Number d8_ = AH.div(Generated_numbers_Test.d2_, Generated_numbers_Test.d6_);
  public static final Number d9_ = AH.div(Generated_numbers_Test.d6_, new BigDecimal("2.22").setScale(2, RoundingMode.DOWN));
  public static final Number dA_ = new BigInteger("5");
  public static final Number dB_ = new BigDecimal("5.00").setScale(2, RoundingMode.DOWN);
  public static final Boolean dC_ = AH.isEqual(Generated_numbers_Test.dA_, Generated_numbers_Test.dB_);
  @Test
  public void Division_item0_8440513089311875332() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("5") + ", but was: " + Generated_numbers_Test.d1_, EqualsTestOp.matches(new BigInteger("5"), Generated_numbers_Test.d1_));
  }
  @Test
  public void Division_item1_8440513089313371258() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("5.00").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.d1_, EqualsTestOp.matches(new BigDecimal("5.00").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.d1_));
  }
  @Test
  public void Division_item2_8440513089313371334() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("5.00000").setScale(5, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.d1_, EqualsTestOp.matches(new BigDecimal("5.00000").setScale(5, RoundingMode.DOWN), Generated_numbers_Test.d1_));
  }
  @Test
  public void Division_item3_8440513089312169123() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("5") + ", but was: " + Generated_numbers_Test.d2_, EqualsTestOp.matches(new BigInteger("5"), Generated_numbers_Test.d2_));
  }
  @Test
  public void Division_item4_8440513089313381995() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("5.00").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.d2_, EqualsTestOp.matches(new BigDecimal("5.00").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.d2_));
  }
  @Test
  public void Division_item5_8440513089313390279() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("1") + ", but was: " + Generated_numbers_Test.d3_, EqualsTestOp.matches(new BigInteger("1"), Generated_numbers_Test.d3_));
  }
  @Test
  public void Division_item6_8440513089313395761() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("0.5555555555").setScale(10, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.d4_, RealEqualsTestOp.matches(Generated_numbers_Test.d4_, new BigDecimal("0.5555555555").setScale(10, RoundingMode.DOWN), 10));
  }
  @Test
  public void Division_item7_8440513089313584642() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("-0.5555555555").setScale(10, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.d5_, RealEqualsTestOp.matches(Generated_numbers_Test.d5_, new BigDecimal("-0.5555555555").setScale(10, RoundingMode.DOWN), 10));
  }
  @Test
  public void Division_item8_8440513089313602302() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("-5.0").setScale(1, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.d6_, EqualsTestOp.matches(new BigDecimal("-5.0").setScale(1, RoundingMode.DOWN), Generated_numbers_Test.d6_));
  }
  @Test
  public void Division_item9_8440513089313626352() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("-1") + ", but was: " + Generated_numbers_Test.d7_, EqualsTestOp.matches(new BigInteger("-1"), Generated_numbers_Test.d7_));
  }
  @Test
  public void Division_item10_8440513089313644574() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("-1") + ", but was: " + Generated_numbers_Test.d8_, EqualsTestOp.matches(new BigInteger("-1"), Generated_numbers_Test.d8_));
  }
  @Test
  public void Division_item11_8440513089313651663() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("-2.2522522522").setScale(10, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.d9_, RealEqualsTestOp.matches(Generated_numbers_Test.d9_, new BigDecimal("-2.2522522522").setScale(10, RoundingMode.DOWN), 10));
  }
  @Test
  public void Division_item13_8440513089312198453() throws Throwable {
    Assert.assertEquals("Expected: " + true + ", but was: " + Generated_numbers_Test.dC_, (Object) true, Generated_numbers_Test.dC_);
  }
  public static final Number t1_ = AH.add(new BigInteger("5"), new BigDecimal("0.22").setScale(2, RoundingMode.DOWN));
  public static final Number t2_ = AH.add(new BigDecimal("5.1").setScale(1, RoundingMode.DOWN), new BigDecimal("5.2").setScale(1, RoundingMode.DOWN));
  public static final Number t3_ = AH.add(new BigDecimal("5.1").setScale(1, RoundingMode.DOWN), Generated_numbers_Test.t1_);
  public static final Number t4_ = new BigDecimal("2.000").setScale(3, RoundingMode.DOWN);
  public static final Number t5_ = AH.add(Generated_numbers_Test.t4_, new BigInteger("2"));
  public static final Number t6_ = AH.add(Generated_numbers_Test.t4_, new BigDecimal("2.00001").setScale(5, RoundingMode.DOWN));
  public static final Number t7_ = AH.mul(Generated_numbers_Test.t4_, new BigInteger("2"));
  public static final Number t8_ = AH.mul(Generated_numbers_Test.t4_, new BigDecimal("2.0001").setScale(4, RoundingMode.DOWN));
  public static final Number t9_ = AH.add(Generated_numbers_Test.t1_, new BigInteger("15"));
  @Test
  public void MixedPrec_item0_8440513089313679141() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("5.22").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t1_, EqualsTestOp.matches(new BigDecimal("5.22").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.t1_));
  }
  @Test
  public void MixedPrec_item1_8440513089313685644() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("10.3").setScale(1, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t2_, EqualsTestOp.matches(new BigDecimal("10.3").setScale(1, RoundingMode.DOWN), Generated_numbers_Test.t2_));
  }
  @Test
  public void MixedPrec_item2_8440513089313685676() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("10.32").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t3_, EqualsTestOp.matches(new BigDecimal("10.32").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.t3_));
  }
  @Test
  public void MixedPrec_item3_8440513089313685712() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("2.0").setScale(1, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t4_, EqualsTestOp.matches(new BigDecimal("2.0").setScale(1, RoundingMode.DOWN), Generated_numbers_Test.t4_));
  }
  @Test
  public void MixedPrec_item4_8440513089313719644() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("2") + ", but was: " + Generated_numbers_Test.t4_, EqualsTestOp.matches(new BigInteger("2"), Generated_numbers_Test.t4_));
  }
  @Test
  public void MixedPrec_item5_8440513089313719704() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("2.00000").setScale(5, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t4_, EqualsTestOp.matches(new BigDecimal("2.00000").setScale(5, RoundingMode.DOWN), Generated_numbers_Test.t4_));
  }
  @Test
  public void MixedPrec_item6_8440513089313685752() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("4") + ", but was: " + Generated_numbers_Test.t5_, EqualsTestOp.matches(new BigInteger("4"), Generated_numbers_Test.t5_));
  }
  @Test
  public void MixedPrec_item7_8440513089313685796() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("4.00001").setScale(5, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t6_, EqualsTestOp.matches(new BigDecimal("4.00001").setScale(5, RoundingMode.DOWN), Generated_numbers_Test.t6_));
  }
  @Test
  public void MixedPrec_item8_8440513089313685844() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("4") + ", but was: " + Generated_numbers_Test.t7_, EqualsTestOp.matches(new BigInteger("4"), Generated_numbers_Test.t7_));
  }
  @Test
  public void MixedPrec_item9_8440513089313769028() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("4.00").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t7_, EqualsTestOp.matches(new BigDecimal("4.00").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.t7_));
  }
  @Test
  public void MixedPrec_item10_8440513089313769096() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("4.0000").setScale(4, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t7_, EqualsTestOp.matches(new BigDecimal("4.0000").setScale(4, RoundingMode.DOWN), Generated_numbers_Test.t7_));
  }
  @Test
  public void MixedPrec_item11_8440513089313685896() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("4.0002000").setScale(7, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t8_, EqualsTestOp.matches(new BigDecimal("4.0002000").setScale(7, RoundingMode.DOWN), Generated_numbers_Test.t8_));
  }
  @Test
  public void MixedPrec_item12_3182514044108770369() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("20.22").setScale(2, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.t9_, EqualsTestOp.matches(new BigDecimal("20.22").setScale(2, RoundingMode.DOWN), Generated_numbers_Test.t9_));
  }
  public static Number nix() {

    return null;
  }
  @Test
  public void OptionalNumbers_item0_1801842150043769915() throws Throwable {
    Assert.assertEquals("Expected: " + "HalloWelt" + ", but was: " + AH.addString("Hallo", "Welt"), "HalloWelt", AH.addString("Hallo", "Welt"));
  }
  @Test
  public void OptionalNumbers_item1_8721870733846009437() throws Throwable {
    Assert.assertEquals("Expected: " + null + ", but was: " + AH.add(null, new BigInteger("1")), (Object) null, AH.add(null, new BigInteger("1")));
  }
  @Test
  public void OptionalNumbers_item2_1801842150045057236() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("6") + ", but was: " + AH.add(new BigInteger("5"), new BigInteger("1")), EqualsTestOp.matches(new BigInteger("6"), AH.add(new BigInteger("5"), new BigInteger("1"))));
  }
  @Test
  public void OptionalNumbers_item3_1801842150043778576() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("11") + ", but was: " + AH.add(AH.mul(new BigInteger("5"), new BigInteger("2")), new BigInteger("1")), EqualsTestOp.matches(new BigInteger("11"), AH.add(AH.mul(new BigInteger("5"), new BigInteger("2")), new BigInteger("1"))));
  }
  @Test
  public void OptionalNumbers_item4_1801842150043783825() throws Throwable {
    Assert.assertEquals("Expected: " + null + ", but was: " + AH.add(AH.mul(null, new BigInteger("2")), new BigInteger("1")), (Object) null, AH.add(AH.mul(null, new BigInteger("2")), new BigInteger("1")));
  }
  @Test
  public void OptionalNumbers_item5_2987720027699272015() throws Throwable {
    Assert.assertEquals("Expected: " + null + ", but was: " + AH.add(Generated_numbers_Test.nix(), new BigInteger("1")), (Object) null, AH.add(Generated_numbers_Test.nix(), new BigInteger("1")));
  }
  public static final Number ten_ = new BigInteger("10");
  @Test
  public void Bounding_item0_4880743667108809417() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("15") + ", but was: " + AH.bounds(AH.mul(Generated_numbers_Test.ten_, new BigInteger("2")), new BigInteger("3"), new BigInteger("15")), EqualsTestOp.matches(new BigInteger("15"), AH.bounds(AH.mul(Generated_numbers_Test.ten_, new BigInteger("2")), new BigInteger("3"), new BigInteger("15"))));
  }
  @Test
  public void Bounding_item1_4880743667109174374() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("3") + ", but was: " + AH.bounds(AH.sub(Generated_numbers_Test.ten_, new BigInteger("8")), new BigInteger("3"), new BigInteger("15")), EqualsTestOp.matches(new BigInteger("3"), AH.bounds(AH.sub(Generated_numbers_Test.ten_, new BigInteger("8")), new BigInteger("3"), new BigInteger("15"))));
  }
  @Test
  public void Bounding_item2_4880743667109536024() throws Throwable {
    Assert.assertTrue("Expected: " + Generated_numbers_Test.ten_ + ", but was: " + AH.bounds(Generated_numbers_Test.ten_, new BigInteger("3"), new BigInteger("15")), EqualsTestOp.matches(Generated_numbers_Test.ten_, AH.bounds(Generated_numbers_Test.ten_, new BigInteger("3"), new BigInteger("15"))));
  }
  public static final Number three33_ = new BigDecimal("3.33").setScale(2, RoundingMode.DOWN);
  @Test
  public void BoundingReal_item0_2098022166928237076() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("5.00").setScale(2, RoundingMode.DOWN) + ", but was: " + AH.bounds(AH.mul(Generated_numbers_Test.three33_, new BigInteger("2")), new BigDecimal("3.00").setScale(2, RoundingMode.DOWN), new BigDecimal("5.00").setScale(2, RoundingMode.DOWN)), EqualsTestOp.matches(new BigDecimal("5.00").setScale(2, RoundingMode.DOWN), AH.bounds(AH.mul(Generated_numbers_Test.three33_, new BigInteger("2")), new BigDecimal("3.00").setScale(2, RoundingMode.DOWN), new BigDecimal("5.00").setScale(2, RoundingMode.DOWN))));
  }
  @Test
  public void BoundingReal_item1_2098022166928256076() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("3.00").setScale(2, RoundingMode.DOWN) + ", but was: " + AH.bounds(AH.div(Generated_numbers_Test.three33_, new BigInteger("2")), new BigDecimal("3.00").setScale(2, RoundingMode.DOWN), new BigDecimal("5.00").setScale(2, RoundingMode.DOWN)), EqualsTestOp.matches(new BigDecimal("3.00").setScale(2, RoundingMode.DOWN), AH.bounds(AH.div(Generated_numbers_Test.three33_, new BigInteger("2")), new BigDecimal("3.00").setScale(2, RoundingMode.DOWN), new BigDecimal("5.00").setScale(2, RoundingMode.DOWN))));
  }
  public static final Number sn1_ = new BigDecimal("2e-5").setScale(5, RoundingMode.DOWN);
  public static final Number sn2_ = new BigDecimal("3.4e3").setScale(0, RoundingMode.DOWN);
  public static final Number sn3_ = AH.add(Generated_numbers_Test.sn1_, Generated_numbers_Test.sn2_);
  public static final Number sn4_ = AH.add(Generated_numbers_Test.sn2_, new BigInteger("340"));
  public static final Number sn5_ = new BigDecimal("1e-5").setScale(5, RoundingMode.DOWN);
  @Test
  public void ScientificNotations_item0_1768187068908767829() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("0.00002").setScale(5, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.sn1_, EqualsTestOp.matches(new BigDecimal("0.00002").setScale(5, RoundingMode.DOWN), Generated_numbers_Test.sn1_));
  }
  @Test
  public void ScientificNotations_item1_1768187068908882947() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("3400") + ", but was: " + Generated_numbers_Test.sn2_, EqualsTestOp.matches(new BigInteger("3400"), Generated_numbers_Test.sn2_));
  }
  @Test
  public void ScientificNotations_item2_1768187068908883020() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("3400.00002").setScale(5, RoundingMode.DOWN) + ", but was: " + Generated_numbers_Test.sn3_, EqualsTestOp.matches(new BigDecimal("3400.00002").setScale(5, RoundingMode.DOWN), Generated_numbers_Test.sn3_));
  }
  @Test
  public void ScientificNotations_item3_1768187068908883342() throws Throwable {
    Assert.assertTrue("Expected: " + new BigInteger("3740") + ", but was: " + Generated_numbers_Test.sn4_, EqualsTestOp.matches(new BigInteger("3740"), Generated_numbers_Test.sn4_));
  }
  @Test
  public void ScientificNotations_item4_1768187068908883868() throws Throwable {
    Assert.assertTrue("Expected: " + AH.mul(new BigInteger("2"), Generated_numbers_Test.sn5_) + ", but was: " + new BigDecimal("2.00e-5").setScale(7, RoundingMode.DOWN), EqualsTestOp.matches(AH.mul(new BigInteger("2"), Generated_numbers_Test.sn5_), new BigDecimal("2.00e-5").setScale(7, RoundingMode.DOWN)));
  }
  @Test
  public void ScientificNotations_item5_1768187068908885677() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("1e-6").setScale(6, RoundingMode.DOWN) + ", but was: " + AH.div(Generated_numbers_Test.sn5_, new BigInteger("10")), EqualsTestOp.matches(new BigDecimal("1e-6").setScale(6, RoundingMode.DOWN), AH.div(Generated_numbers_Test.sn5_, new BigInteger("10"))));
  }
  @Test
  public void ScientificNotations_item6_1768187068908888104() throws Throwable {
    Assert.assertTrue("Expected: " + new BigDecimal("1e5").setScale(0, RoundingMode.DOWN) + ", but was: " + AH.mul(new BigDecimal("1e10").setScale(0, RoundingMode.DOWN), new BigDecimal("1e-5").setScale(5, RoundingMode.DOWN)), EqualsTestOp.matches(new BigDecimal("1e5").setScale(0, RoundingMode.DOWN), AH.mul(new BigDecimal("1e10").setScale(0, RoundingMode.DOWN), new BigDecimal("1e-5").setScale(5, RoundingMode.DOWN))));
  }




}
