package test.org.iets3.variability.featuremodel.base.checking_rules;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.test.runtime.CheckExpectedMessageRunnable;
import jetbrains.mps.errors.MessageStatus;
import jetbrains.mps.smodel.SNodePointer;

@MPSLaunch
public class CheckMissingValueForFeatureNotPresent_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(CheckMissingValueForFeatureNotPresent_Test.class).projectPath(null).modelRef("r:24a667d9-96b7-4b98-90dc-d2adc89d96f8(test.org.iets3.variability.featuremodel.base.checking_rules@tests)").reopenProject(null).build());

  public CheckMissingValueForFeatureNotPresent_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_NodeAttributeUsedInConstraintCheck4782337335699992343() throws Throwable {
    new TestBody(this).test_NodeAttributeUsedInConstraintCheck4782337335699992343();
  }
  @Test
  public void test_NodeAttributeUsedInConstraintCheck4782337335703131027() throws Throwable {
    new TestBody(this).test_NodeAttributeUsedInConstraintCheck4782337335703131027();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    protected void initTestNodes() {
      prepareTestNodes("3050013027466900090");
    }

    public void test_NodeAttributeUsedInConstraintCheck4782337335699992343() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getNodeById("4782337335699992127");
        new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(nodeToCheck, MessageStatus.WARNING, new SNodePointer("r:ea20ecfb-5cc1-4867-966a-b2976cfc5ae3(org.iets3.variability.featuremodel.base.typesystem)", "7478266977560638158"), "", myProject.getRepository(), myProject.getPlatform()).run();
      });
    }
    public void test_NodeAttributeUsedInConstraintCheck4782337335703131027() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getNodeById("4782337335701629149");
        new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(nodeToCheck, MessageStatus.WARNING, new SNodePointer("r:ea20ecfb-5cc1-4867-966a-b2976cfc5ae3(org.iets3.variability.featuremodel.base.typesystem)", "7478266977560638158"), "", myProject.getRepository(), myProject.getPlatform()).run();
      });
    }

  }
}
