package org.iets3.components.functional.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.iets3.components.core.behavior.AbstractComponentInterface__BehaviorDescriptor;
import org.iets3.components.core.behavior.Component__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class ProducesPortRef_Constraints extends BaseConstraintsDescriptor {
  /*package*/ ProducesPortRef_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.ProducesPortRef$Z0, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.port$6ccY, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:f851cd61-8f8d-4520-ace8-e456afe93904(org.iets3.components.functional.constraints)", "4649601490453561053");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forResolvableElements(Sequence.fromIterable(AbstractComponentInterface__BehaviorDescriptor.ports_idx8tpSA8agB.invoke(Component__BehaviorDescriptor.compInterface_idx8tpSA1cCO.invoke(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.Component$gR, true, false)))).where((it) -> SNodeOperations.isInstanceOf(SLinkOperations.getTarget(it, LINKS.category$WD4l), CONCEPTS.ProducesPortCategory$f1)));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ProducesPortRef$Z0 = MetaAdapterFactory.getConcept(0x257976063fb647b8L, 0xbc3cb4384df7da44L, 0x4086b3ebc19c7bfdL, "org.iets3.components.functional.structure.ProducesPortRef");
    /*package*/ static final SConcept Component$gR = MetaAdapterFactory.getConcept(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x6c4f9fd23e484601L, "org.iets3.components.core.structure.Component");
    /*package*/ static final SConcept ProducesPortCategory$f1 = MetaAdapterFactory.getConcept(0x257976063fb647b8L, 0xbc3cb4384df7da44L, 0x5aed9484f65f2b0L, "org.iets3.components.functional.structure.ProducesPortCategory");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink port$6ccY = MetaAdapterFactory.getReferenceLink(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x4086b3ebc195c2b2L, 0x4086b3ebc195cc40L, "port");
    /*package*/ static final SContainmentLink category$WD4l = MetaAdapterFactory.getContainmentLink(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x6c4f9fd23e51937cL, 0x5aed9484f65f1e5L, "category");
  }
}
