package org.iets3.core.expr.simpleTypes.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.iets3.core.expr.base.plugin.InfHelper;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.iets3.core.expr.base.behavior.ISupportHexValues__BehaviorDescriptor;
import org.iets3.core.expr.base.runtime.runtime.PTF;
import org.iets3.core.expr.base.behavior.HexValue__BehaviorDescriptor;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class NumberRangeSpec_Constraints extends BaseConstraintsDescriptor {
  /*package*/ NumberRangeSpec_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.NumberRangeSpec$3n, initContext);
    record(new Max_PD(this));
    record(new Min_PD(this));
  }

  /*package*/ static final class Max_PD extends BasePropertyConstraintsDescriptor {
    public Max_PD(ConstraintsDescriptor container) {
      super(PROPS.max$7P3H, container, true, true, true);
    }
    @Override
    public Object getValue(SNode node) {
      return (isNotEmptyString(SPropertyOperations.getString(node, PROPS.max$7P3H)) ? SPropertyOperations.getString(node, PROPS.max$7P3H) : InfHelper.POSINF);
    }
    @Override
    public void setPropertyValue(SNode node, Object propertyValue) {
      staticSetPropertyValue(node, SPropertyOperations.castString(propertyValue));
    }
    private static void staticSetPropertyValue(SNode node, String propertyValue) {
      SConcept hexConcept = CONCEPTS.HexValue$1m;
      SProperty property = PROPS.max$7P3H;

      if ((propertyValue == null || propertyValue.length() == 0) || propertyValue.equals(InfHelper.POSINF)) {
        SPropertyOperations.assign(node, PROPS.max$7P3H, InfHelper.POSINF);
        SNodeOperations.deleteNode(ISupportHexValues__BehaviorDescriptor.getHexValue_id2KEzU_jNnNP.invoke(node, property));
      } else if (PTF.areHexadecimalNumbersSupported(node) && (boolean) HexValue__BehaviorDescriptor.isHexaDecimal_id5Ys_ngSnA9D.invoke(SNodeOperations.asSConcept(hexConcept), propertyValue)) {
        SNode hexValue = ISupportHexValues__BehaviorDescriptor.setHexValue_id6QsMU1GWQsW.invoke(node, property, propertyValue, ((boolean) false));
        SPropertyOperations.assign(node, PROPS.max$7P3H, HexValue__BehaviorDescriptor.toNumber_id5Ys_ngSnY$C.invoke(hexValue).toString());
      } else {
        SPropertyOperations.assign(node, PROPS.max$7P3H, propertyValue);
        SNodeOperations.deleteNode(ISupportHexValues__BehaviorDescriptor.getHexValue_id2KEzU_jNnNP.invoke(node, property));
      }
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e3651d26-951a-4ffc-9443-e8b8de452a77(org.iets3.core.expr.simpleTypes.constraints)", "3989687176992809631"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      if ((propertyValue == null || propertyValue.length() == 0) || propertyValue.equals(InfHelper.POSINF) || ((boolean) HexValue__BehaviorDescriptor.isHexaDecimal_id5Ys_ngSnA9D.invoke(SNodeOperations.asSConcept(CONCEPTS.HexValue$1m), propertyValue) && PTF.areHexadecimalNumbersSupported(node))) {
        return true;
      }
      try {
        Double.parseDouble(propertyValue.replace(',', '.'));
        return true;
      } catch (NumberFormatException ex) {
        return false;
      }
    }
    private static boolean isNotEmptyString(String str) {
      return str != null && str.length() > 0;
    }
  }
  /*package*/ static final class Min_PD extends BasePropertyConstraintsDescriptor {
    public Min_PD(ConstraintsDescriptor container) {
      super(PROPS.min$7OOG, container, true, true, true);
    }
    @Override
    public Object getValue(SNode node) {
      return (isNotEmptyString(SPropertyOperations.getString(node, PROPS.min$7OOG)) ? SPropertyOperations.getString(node, PROPS.min$7OOG) : InfHelper.NEGINF);
    }
    @Override
    public void setPropertyValue(SNode node, Object propertyValue) {
      staticSetPropertyValue(node, SPropertyOperations.castString(propertyValue));
    }
    private static void staticSetPropertyValue(SNode node, String propertyValue) {
      SConcept hexConcept = CONCEPTS.HexValue$1m;
      SProperty property = PROPS.min$7OOG;
      if ((propertyValue == null || propertyValue.length() == 0) || propertyValue.equals(InfHelper.NEGINF)) {
        SPropertyOperations.assign(node, PROPS.min$7OOG, InfHelper.NEGINF);
        SNodeOperations.deleteNode(ISupportHexValues__BehaviorDescriptor.getHexValue_id2KEzU_jNnNP.invoke(node, property));
      } else if (PTF.areHexadecimalNumbersSupported(node) && (boolean) HexValue__BehaviorDescriptor.isHexaDecimal_id5Ys_ngSnA9D.invoke(SNodeOperations.asSConcept(hexConcept), propertyValue)) {
        SNode hexValue = ISupportHexValues__BehaviorDescriptor.setHexValue_id6QsMU1GWQsW.invoke(node, property, propertyValue, ((boolean) false));
        SPropertyOperations.assign(node, PROPS.min$7OOG, HexValue__BehaviorDescriptor.toNumber_id5Ys_ngSnY$C.invoke(hexValue).toString());
      } else {
        SPropertyOperations.assign(node, PROPS.min$7OOG, propertyValue);
        SNodeOperations.deleteNode(ISupportHexValues__BehaviorDescriptor.getHexValue_id2KEzU_jNnNP.invoke(node, property));
      }
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e3651d26-951a-4ffc-9443-e8b8de452a77(org.iets3.core.expr.simpleTypes.constraints)", "3989687176992774237"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      if ((propertyValue == null || propertyValue.length() == 0) || propertyValue.equals(InfHelper.NEGINF) || (PTF.areHexadecimalNumbersSupported(node) && (boolean) HexValue__BehaviorDescriptor.isHexaDecimal_id5Ys_ngSnA9D.invoke(SNodeOperations.asSConcept(CONCEPTS.HexValue$1m), propertyValue))) {
        return true;
      }
      try {
        Double.parseDouble(propertyValue.replace(',', '.'));
        return true;
      } catch (NumberFormatException ex) {
        return false;
      }


    }
    private static boolean isNotEmptyString(String str) {
      return str != null && str.length() > 0;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept NumberRangeSpec$3n = MetaAdapterFactory.getConcept(0x6b277d9ad52d416fL, 0xa2091919bd737f50L, 0x127541598201af65L, "org.iets3.core.expr.simpleTypes.structure.NumberRangeSpec");
    /*package*/ static final SConcept HexValue$1m = MetaAdapterFactory.getConcept(0xcfaa4966b7d54b69L, 0xb66a309a6e1a7290L, 0x5f9c9574385e6251L, "org.iets3.core.expr.base.structure.HexValue");
  }

  private static final class PROPS {
    /*package*/ static final SProperty max$7P3H = MetaAdapterFactory.getProperty(0x6b277d9ad52d416fL, 0xa2091919bd737f50L, 0x127541598201af65L, 0x127541598201af70L, "max");
    /*package*/ static final SProperty min$7OOG = MetaAdapterFactory.getProperty(0x6b277d9ad52d416fL, 0xa2091919bd737f50L, 0x127541598201af65L, 0x127541598201af6fL, "min");
  }
}
