package org.iets3.components.core.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import com.mbeddr.core.base.behavior.AbstractTreeViewNode;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.iets3.core.base.behavior.IValidNamedConcept__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import com.mbeddr.core.base.behavior.NodeTreeViewNode;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import com.mbeddr.core.base.behavior.TreeViewAction;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import javax.swing.Icon;
import jetbrains.mps.ide.icons.GlobalIconManager;
import jetbrains.mps.project.Project;
import jetbrains.mps.openapi.navigation.NavigationSupport;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public final class AbstractComponentInstanceWithRef__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x2fa41bd61d1549deL, "org.iets3.components.core.structure.AbstractComponentInstanceWithRef");

  public static final SMethod<String> getAutomaticName_idcJpacq408C = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getAutomaticName").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(229512757698888232L).languageId(0xbd9c05c0f8725a35L, 0x7b68d745a7b848b9L).build2();
  public static final SMethod<AbstractTreeViewNode> getTreeNode_id7NyyyjNtbn2 = new SMethodBuilder<AbstractTreeViewNode>(new SJavaCompoundTypeImpl(AbstractTreeViewNode.class)).name("getTreeNode").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8998906896747640258L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<SNode> component_id77HYM7H$sfU = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("component").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8209493818904527866L).languageId(0xb6713d118449c6e7L, 0xf0fd486f857743e9L).build2();
  public static final SMethod<Iterable<SNode>> parameterValues_id3xTZ$YBvTdz = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("parameterValues").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4069563356371981155L).languageId(0xb6713d118449c6e7L, 0xf0fd486f857743e9L).build2();
  public static final SMethod<Boolean> isInline_id3xTZ$YBw7Op = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isInline").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4069563356372040985L).languageId(0xb6713d118449c6e7L, 0xf0fd486f857743e9L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getAutomaticName_idcJpacq408C, getTreeNode_id7NyyyjNtbn2, component_id77HYM7H$sfU, parameterValues_id3xTZ$YBvTdz, isInline_id3xTZ$YBw7Op);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getAutomaticName_idcJpacq408C(@NotNull SNode __thisNode__) {
    return (String) IValidNamedConcept__BehaviorDescriptor.getIdentifierName_id7NEp8pMMUwS.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(__thisNode__, LINKS.component$xlLY), LINKS.ref$KPLr));
  }
  /*package*/ static AbstractTreeViewNode getTreeNode_id7NyyyjNtbn2(@NotNull SNode __thisNode__, final String cat) {
    final SNode thisNode = __thisNode__;

    String label = SPropertyOperations.getString(thisNode, PROPS.name$MnvL);
    if (SLinkOperations.getTarget(thisNode, LINKS.optionalName$AhFr) != null) {
      label += ": " + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, LINKS.component$xlLY), LINKS.ref$KPLr), PROPS.name$MnvL);
    }
    return new NodeTreeViewNode(thisNode, label, Component__BehaviorDescriptor.getComponentIconSmall_id7jwD7MQjeSk.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, LINKS.component$xlLY), LINKS.ref$KPLr)), cat, new String[]{"structure"}) {
      public int getChildCountFromModel() {
        int instances = Sequence.fromIterable(SNodeOperations.ofConcept(Component__BehaviorDescriptor.allSubstructure_idsiw10FnrMt.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, LINKS.component$xlLY), LINKS.ref$KPLr)), CONCEPTS.AbstractComponentInstanceBase$QW)).count();
        int connectors = Sequence.fromIterable(SNodeOperations.ofConcept(Component__BehaviorDescriptor.allSubstructure_idsiw10FnrMt.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, LINKS.component$xlLY), LINKS.ref$KPLr)), CONCEPTS.AbstractPortToPortConnector$JI)).count();
        return instances + connectors;
      }
      public List<AbstractTreeViewNode> getChildrenFromModel() {
        return getTheirTreeNodes(Sequence.fromIterable(SNodeOperations.ofConcept(Component__BehaviorDescriptor.allSubstructure_idsiw10FnrMt.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, LINKS.component$xlLY), LINKS.ref$KPLr)), CONCEPTS.AbstractComponentInstanceBase$QW)).union(Sequence.fromIterable(SNodeOperations.ofConcept(Component__BehaviorDescriptor.allSubstructure_idsiw10FnrMt.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, LINKS.component$xlLY), LINKS.ref$KPLr)), CONCEPTS.AbstractPortToPortConnector$JI))), cat);
      }
      @Override
      public List<TreeViewAction> getActions() {
        final Wrappers._T<SNode> c = new Wrappers._T<SNode>();
        final Wrappers._T<Icon> icon = new Wrappers._T<Icon>();
        SNodeOperations.getModel(__thisNode__).getRepository().getModelAccess().runReadAction(() -> {
          c.value = SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, LINKS.component$xlLY), LINKS.ref$KPLr);
          icon.value = GlobalIconManager.getInstance().getIconFor(c.value);
        });
        final SNode finalC = c.value;
        return oneAction(new TreeViewAction("Select Component in Editor", icon.value) {
          public void execute(final AbstractTreeViewNode treeNode, final Project project) {
            SNodeOperations.getModel(__thisNode__).getRepository().getModelAccess().runWriteAction(() -> NavigationSupport.getInstance().openNode(project, finalC, true, true));
          }
        });
      }
    };
  }
  /*package*/ static SNode component_id77HYM7H$sfU(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(__thisNode__, LINKS.component$xlLY), LINKS.ref$KPLr);
  }
  /*package*/ static Iterable<SNode> parameterValues_id3xTZ$YBvTdz(@NotNull SNode __thisNode__) {
    return SLinkOperations.getChildren(__thisNode__, LINKS.parameterValues$X3HT);
  }
  /*package*/ static boolean isInline_id3xTZ$YBw7Op(@NotNull SNode __thisNode__) {
    return false;
  }

  /*package*/ AbstractComponentInstanceWithRef__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getAutomaticName_idcJpacq408C(node));
      case 1:
        return (T) ((AbstractTreeViewNode) getTreeNode_id7NyyyjNtbn2(node, (String) parameters[0]));
      case 2:
        return (T) ((SNode) component_id77HYM7H$sfU(node));
      case 3:
        return (T) ((Iterable<SNode>) parameterValues_id3xTZ$YBvTdz(node));
      case 4:
        return (T) ((Boolean) isInline_id3xTZ$YBw7Op(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink component$xlLY = MetaAdapterFactory.getContainmentLink(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x2fa41bd61d1549deL, 0x2fa41bd61d154b21L, "component");
    /*package*/ static final SReferenceLink ref$KPLr = MetaAdapterFactory.getReferenceLink(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x6c4f9fd23e4b67eeL, 0x6c4f9fd23e4b67efL, "ref");
    /*package*/ static final SContainmentLink optionalName$AhFr = MetaAdapterFactory.getContainmentLink(0x7b68d745a7b848b9L, 0xbd9c05c0f8725a35L, 0x32f64a31a100207L, 0x32f64a31a1004e8L, "optionalName");
    /*package*/ static final SContainmentLink parameterValues$X3HT = MetaAdapterFactory.getContainmentLink(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x2fa41bd61d1549deL, 0x2fa41bd61d154d21L, "parameterValues");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractComponentInstanceBase$QW = MetaAdapterFactory.getConcept(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x71edfb21ed616471L, "org.iets3.components.core.structure.AbstractComponentInstanceBase");
    /*package*/ static final SConcept AbstractPortToPortConnector$JI = MetaAdapterFactory.getConcept(0xf0fd486f857743e9L, 0xb6713d118449c6e7L, 0x5aed9485017fe26L, "org.iets3.components.core.structure.AbstractPortToPortConnector");
  }
}
